### ISSUE TITLE
Using multiple embedded Hawtio instances on one machine/user can error on startup

### ISSUE THREAD

**Issue by alex-sherwin** [hawtio/hawtio#1208]
When starting up multiple applications on the same machine as the same user, sometimes embedded hawtio fails.  All the embedded apps are hardcoded inside io.hawt.embedded.Main.run() to use ~/.hawtio/tmp as the temp directory.

During the jetty WebAppContext initialization, if the tmp dir is non-persistent, it attempts to delete/recreate it, which will fail occassionally with multiple apps starting at the same time

```
2014/04/08 09:14:10.924 [main] WARN [org.eclipse.jetty.webapp.WebAppContext:501] - Failed startup of context o.e.j.w.WebAppContext@697f186a{/hawtio,null,null}{apps/hawtio/hawtio-web-1.2.2.war}
java.lang.IllegalStateException: Failed to delete temp dir /home/acadiait/.hawtio/tmp
        at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:372) ~[jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:260) ~[jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69) ~[jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:455) ~[jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:491) ~[jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:117) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.server.Server.start(Server.java:355) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:99) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.server.Server.doStart(Server.java:324) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-all-9.1.2.v20140210.jar:9.1.2.v20140210]
        at io.hawt.embedded.Main.run(Main.java:109) [hawtio-embedded-1.2.2.jar:na]
```

**Comment by davsclaus** [comment]
ok as is
