### ISSUE TITLE
master branch probably shouldn't be displayed in the wiki when using fabric

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#1418]
as you get lots of Version 'master' does not exist exceptions
```
<p>io.fabric8.api.FabricException: Version 'master' does not exist</p>
<p>	at io.fabric8.service.FabricServiceImpl.getVersion(FabricServiceImpl.java:963)</p>
<p>	at io.fabric8.api.jmx.FabricManager.getProfile(FabricManager.java:812)</p>
<p>	at io.fabric8.api.jmx.FabricManager.getProfile(FabricManager.java:808)</p>
```

**Comment by davsclaus** [comment]
closing fabric v1 tickets, ENH requires is tracked on jboss fuse side.
