### ISSUE TITLE
NPE when accessing index.html on wildfly-8.1.0

### ISSUE THREAD

**Issue by tdiesler** [hawtio/hawtio#1651]
hawtio-default-1.4.24

```
16:10:21,394 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: WildFly 8.1.0.Final "Kenny" started in 10075ms - Started 359 of 413 services (100 services are lazy, passive or on-demand)
16:10:36,886 ERROR [io.undertow.request] (default task-3) UT005023: Exception handling request to /hawtio/index.html: java.lang.NullPointerException
	at io.hawt.web.SessionExpiryFilter.process(SessionExpiryFilter.java:71) [hawtio-system-1.4.24.jar:1.4.24]
	at io.hawt.web.SessionExpiryFilter.doFilter(SessionExpiryFilter.java:47) [hawtio-system-1.4.24.jar:1.4.24]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.0.15.Final.jar:1.0.15.Final]
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
```

I have this in my config

```
    <system-properties>
		<property name="hawtio.authenticationEnabled" value="false" />
    </system-properties>
```

**Comment by davsclaus** [comment]
reopen if still a problem
