### ISSUE TITLE
Karaf 3.0.2 Insufficient roles/credentials for operation on installation

### ISSUE THREAD

**Issue by kurailicious** [hawtio/hawtio#1747]
Whenever I try to install Hawt.io on a fresh installation of Karaf 3.0.2 I get a Insufficient roles/credentials for operation exception. The exception log is listed below. 

```
2014-11-16 10:36:55,924 | INFO  | pool-56-thread-1 | AuthenticationFilter             | 233 - io.hawt.hawtio-web - 1.4.31 | Starting hawtio authentication filter, JAAS realm: "karaf" authorized role(s): "admin,viewer" role principal classes: "org.apache.karaf.jaas.boot.principal.RolePrincipal,org.apache.karaf.jaas.modules.RolePrincipal,org.apache.karaf.jaas.boot.principal.GroupPrincipal"
2014-11-16 10:36:55,993 | INFO  | pool-56-thread-1 | hawtio-web - 233}                | 66 - org.eclipse.jetty.aggregate.jetty-all-server - 8.1.15.v20140411 | jolokia-agent: No access restrictor found at classpath:/jolokia-access.xml, access to all MBeans is allowed
2014-11-16 10:36:56,123 | WARN  | pool-56-thread-1 | hawtio-web - 233}                | 66 - org.eclipse.jetty.aggregate.jetty-all-server - 8.1.15.v20140411 | jolokia-agent: Error while using detector ActiveMQDetector: java.lang.SecurityException: Insufficient roles/credentials for operation
java.lang.SecurityException: Insufficient roles/credentials for operation
	at org.apache.karaf.management.KarafMBeanServerGuard.handleInvoke(KarafMBeanServerGuard.java:274)[181:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.KarafMBeanServerGuard.handleGetAttribute(KarafMBeanServerGuard.java:207)[181:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.KarafMBeanServerGuard.invoke(KarafMBeanServerGuard.java:74)[181:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.boot.KarafMBeanServerBuilder$MBeanInvocationHandler.invoke(KarafMBeanServerBuilder.java:63)[karaf-jmx-boot.jar:]
	at com.sun.proxy.$Proxy0.getAttribute(Unknown Source)[:]
	at org.jolokia.detector.AbstractServerDetector$1.execute(AbstractServerDetector.java:108)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.detector.AbstractServerDetector$1.execute(AbstractServerDetector.java:105)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.executor.AbstractMBeanServerExecutor.call(AbstractMBeanServerExecutor.java:90)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.detector.AbstractServerDetector.getAttributeValue(AbstractServerDetector.java:94)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.detector.AbstractServerDetector.getSingleStringAttribute(AbstractServerDetector.java:129)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.detector.ActiveMQDetector.detect(ActiveMQDetector.java:15)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.MBeanServerHandler.detectServers(MBeanServerHandler.java:228)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.MBeanServerHandler.initServerHandle(MBeanServerHandler.java:81)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.MBeanServerHandler.<init>(MBeanServerHandler.java:70)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.LocalRequestDispatcher.<init>(LocalRequestDispatcher.java:71)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.BackendManager.init(BackendManager.java:328)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.BackendManager.<init>(BackendManager.java:130)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.backend.BackendManager.<init>(BackendManager.java:105)[233:io.hawt.hawtio-web:1.4.31]
	at org.jolokia.http.AgentServlet.init(AgentServlet.java:162)[233:io.hawt.hawtio-web:1.4.31]
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)[66:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
```

**Comment by davsclaus** [comment]
closing old tickets.
