### ISSUE TITLE
Installing hawtio logs exception in karaf

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#1811]
Installing latest code on Apache Karaf 2.4.0 causes
```
  Apache Karaf (2.4.0)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'osgi:shutdown' or 'logout' to shutdown Karaf.

karaf@root> features:chooseurl hawtio 1.5-SNAPSHOT
Adding feature url mvn:io.hawt/hawtio-karaf/1.5-SNAPSHOT/xml/features
karaf@root> features:
features:addurl              features:chooseurl           features:info                features:install
features:list                features:listrepositories    features:listurl             features:listversions
features:refreshurl          features:removerepository    features:removeurl           features:uninstall
karaf@root> features:install hawtio
hawtio                        hawtio-core                   hawtio-dev-mode               hawtio-fabric8-branding
hawtio-git                    hawtio-irc-example            hawtio-karaf-git              hawtio-karaf-terminal
hawtio-maven-indexer          hawtio-offline                hawtio-redhat-amq-branding    hawtio-redhat-fuse-branding
hawtio-simple-example         hawtio-social-example
karaf@root> features:install hawtio
karaf@root> Exception in thread "MavenIndexerFacade startup timer" java.lang.IllegalAccessError: tried to access method com.google.common.collect.MapMaker.makeComputingMap(Lcom/google/common/base/Function;)Ljava/util/concurrent/ConcurrentMap; from class com.google.inject.internal.Annotations$AnnotationChecker
	at com.google.inject.internal.Annotations$AnnotationChecker.<init>(Annotations.java:104)
	at com.google.inject.internal.Annotations.<clinit>(Annotations.java:122)
	at com.google.inject.Key.ensureRetainedAtRuntime(Key.java:362)
	at com.google.inject.Key.strategyFor(Key.java:354)
	at com.google.inject.Key.get(Key.java:222)
	at org.sonatype.guice.bean.binders.ParameterKeys.<clinit>(ParameterKeys.java:22)
	at org.codehaus.plexus.DefaultPlexusContainer$ContainerModule.configure(DefaultPlexusContainer.java:825)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.spi.Elements.getElements(Elements.java:80)
	at org.sonatype.guice.bean.binders.MergedModule.configure(MergedModule.java:53)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:230)
	at com.google.inject.spi.Elements.getElements(Elements.java:103)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:136)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:476)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:202)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:166)
	at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:160)
	at io.hawt.maven.indexer.MavenIndexerFacade.init(MavenIndexerFacade.java:72)
	at io.hawt.maven.indexer.AsyncMavenIndexerFacadeFactory.createMavenIndexer(AsyncMavenIndexerFacadeFactory.java:134)
	at io.hawt.maven.indexer.AsyncMavenIndexerFacadeFactory$1.run(AsyncMavenIndexerFacadeFactory.java:49)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by davsclaus** [comment]
Latest code works on karaf 2.4.x now
