### ISSUE TITLE
Security issue - Insufficient roles/credentials for operation - when trying to access mbean "hawtio:type=plugin,name=my-plugin"

### ISSUE THREAD

**Issue by lichtin** [hawtio/hawtio#1873]
Getting a "Security issue accessing mbean" with Hawtio running within a Karaf.
The other plugins come up fine, but not my plugin.

```
2015-01-20 12:27:42,252 | WARN  | qtp1583430966-1078       | PluginServlet                    | io.hawt.web.PluginServlet          79 | 179 - io.hawt.hawtio-web - 1.4.45 | Security issue accessing mbean: hawtio:type=plugin,name=my-plugin
java.lang.SecurityException: Insufficient roles/credentials for operation
	at org.apache.karaf.management.KarafMBeanServerGuard.handleInvoke(KarafMBeanServerGuard.java:274)[53:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.KarafMBeanServerGuard.handleGetAttribute(KarafMBeanServerGuard.java:207)[53:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.KarafMBeanServerGuard.handleGetAttributes(KarafMBeanServerGuard.java:212)[53:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.KarafMBeanServerGuard.invoke(KarafMBeanServerGuard.java:76)[53:org.apache.karaf.management.server:3.0.2]
	at org.apache.karaf.management.boot.KarafMBeanServerBuilder$MBeanInvocationHandler.invoke(KarafMBeanServerBuilder.java:63)[karaf-jmx-boot.jar:]
	at com.sun.proxy.$Proxy0.getAttributes(Unknown Source)[:]
	at io.hawt.web.PluginServlet.doGet(PluginServlet.java:73)[179:io.hawt.hawtio-web:1.4.45]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)[65:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[65:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at io.hawt.web.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:28)[179:io.hawt.hawtio-web:1.4.45]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at io.hawt.web.CORSFilter.doFilter(CORSFilter.java:42)[179:io.hawt.hawtio-web:1.4.45]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at io.hawt.web.CacheHeadersFilter.doFilter(CacheHeadersFilter.java:37)[179:io.hawt.hawtio-web:1.4.45]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at io.hawt.web.SessionExpiryFilter.process(SessionExpiryFilter.java:115)[179:io.hawt.hawtio-web:1.4.45]
	at io.hawt.web.SessionExpiryFilter.doFilter(SessionExpiryFilter.java:47)[179:io.hawt.hawtio-web:1.4.45]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.internal.WelcomeFilesFilter.doFilter(WelcomeFilesFilter.java:185)[79:org.ops4j.pax.web.pax-web-runtime:3.1.2]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[80:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[80:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:77)[80:org.ops4j.pax.web.pax-web-jetty:3.1.2]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[71:org.eclipse.jetty.aggregate.jetty-all-server:8.1.15.v20140411]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_25]
```
Any idea where the issue could be?

**Comment by davsclaus** [comment]
You need to configure my-plugin with the karaf rbac security stuff.

If you install your plugin using a karaf feature you can define it there as we do for hawtio itself
https://github.com/hawtio/hawtio/blob/master/hawtio-karaf/src/main/resources/features.xml#L18

I can't remember the syntax but there is some special meaning with the name you put after "jmx.acl.". Also you can take a look at all the jmx.acl. files in the karaf etc dir

**Comment by lichtin** [comment]
Ah thanks, I see.. As I install 'only' hawtio-core', this config setting does not happen.
Have to do it in my feature file for the moment, but it would make sense if you move

```
<config name="jmx.acl.hawtio.plugin">
* = *
</config>
```

to the "hawtio-core" section?

**Comment by davsclaus** [comment]
Ah yeah that can be a good idea. a PR is welcome to do that

**Comment by davsclaus** [comment]
Thanks for the PR. I have merged it.

Did that help your use-case?

**Comment by lichtin** [comment]
Yes, my plugin came up fine after the change.

**Comment by davsclaus** [comment]
Thanks
