### ISSUE TITLE
Hawtio sample does not work anymore with 1.5-SNASPHOT

### ISSUE THREAD

**Issue by cmoulliard** [hawtio/hawtio#1880]
When launching **mvn jetty:run** command under folder (hawtio/sample) and opening hawtio into the web browser, we get a **Service unavailable- Error HTTP 503**

Some warning are reported about class not found

Here is the log : 

```
mvn jetty:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sample 1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> jetty-maven-plugin:7.6.9.v20130131:run (default-cli) > test-compile @ sample >>>
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/hawt/hawtio-default/1.5-SNAPSHOT/maven-metadata.xml
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/hawt/hawtio-default/1.5-SNAPSHOT/maven-metadata.xml (977 B at 0.6 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/hawt/hawtio-default/1.5-SNAPSHOT/hawtio-default-1.5-20140605.215628-1.pom
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/hawt/hawtio-default/1.5-SNAPSHOT/hawtio-default-1.5-20140605.215628-1.pom (7 KB at 12.2 KB/sec)
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/hawt/hawtio-default/1.5-SNAPSHOT/hawtio-default-1.5-20140605.215628-1.war
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/hawt/hawtio-default/1.5-SNAPSHOT/hawtio-default-1.5-20140605.215628-1.war (25974 KB at 777.1 KB/sec)
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ sample ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ sample ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ sample ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ sample ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample && git rev-parse --verify HEAD
[INFO] Working directory: /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample
[INFO] Storing buildNumber: 9a58071ff425841b6dcf474dee98694f9dfe1506 at timestamp: 1422601974853
[INFO] Executing: /bin/sh -c cd /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample && git rev-parse --verify HEAD
[INFO] Working directory: /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample
[INFO] Storing buildScmBranch: UNKNOWN
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ sample ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ sample ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ sample ---
[INFO] No sources to compile
[INFO]
[INFO] <<< jetty-maven-plugin:7.6.9.v20130131:run (default-cli) < test-compile @ sample <<<
[INFO]
[INFO] --- jetty-maven-plugin:7.6.9.v20130131:run (default-cli) @ sample ---
[INFO] Configuring Jetty for project: sample
[INFO] webAppSourceDirectory does not exist. Defaulting to /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/target/classes
[INFO] Context path = /hawtio
[INFO] Tmp directory = /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp
2015-01-30 08:12:55.470:INFO:oejs.Server:jetty-7.6.9.v20130131
2015-01-30 08:12:56.038:INFO:omjp.MavenWebInfConfiguration:Adding overlay: file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/target/tmp/hawtio-default-1_5-SNAPSHOT_war/
2015-01-30 08:12:57.150:INFO:oejpw.PlusConfiguration:No Transaction manager found - if your webapp requires one, please configure one.
2015-01-30 08:12:57.222:WARN:oejw.StandardDescriptorProcessor:Could not instantiate listener io.hawt.blueprint.HawtioBlueprintContextListener
java.lang.ClassNotFoundException: io.hawt.blueprint.HawtioBlueprintContextListener
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
    at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1486)
    at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1365)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
    at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
    at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:326)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1236)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:689)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480)
    at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:256)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
    at org.eclipse.jetty.server.Server.doStart(Server.java:279)
    at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:520)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:365)
    at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:521)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-01-30 08:12:57.533:INFO:/hawtio:Initializing Spring root WebApplicationContext
INFO  | main | Root WebApplicationContext: initialization started
INFO  | main | Refreshing Root WebApplicationContext: startup date [Fri Jan 30 08:12:57 CET 2015]; root of context hierarchy
INFO  | main | Loading XML bean definitions from ServletContext resource [/WEB-INF/applicationContext.xml]
INFO  | main | Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@b038c21: defining beans [org.apache.activemq.xbean.XBeanBrokerService#0,managementName,activemq,template,consumerTemplate,camel-1:beanPostProcessor,camel-1]; root of factory hierarchy
INFO  | main | Using Persistence Adapter: MemoryPersistenceAdapter
INFO  | JMX connector | JMX consoles can connect to service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
INFO  | main | Apache ActiveMQ 5.10.0 (localhost, ID:dabouhost-57580-1422601978966-0:1) is starting
INFO  | main | Listening for connections at: tcp://localhost:31313
INFO  | main | Connector tcp://localhost:31313 started
INFO  | main | Apache ActiveMQ 5.10.0 (localhost, ID:dabouhost-57580-1422601978966-0:1) started
INFO  | main | For help or more information please see: http://activemq.apache.org
INFO  | main | Using custom ManagementNamingStrategy: org.apache.camel.management.DefaultManagementNamingStrategy@703c3276
INFO  | main | Apache Camel 2.14.1 (CamelContext: camel-1) is starting
INFO  | main | JMX is enabled
INFO  | main | Loaded 182 type converters
INFO  | main | AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
INFO  | main | StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
INFO  | main | Endpoint is configured with noop=true so forcing endpoint to be idempotent as well
INFO  | main | Using default memory based idempotent repository with cache max size: 1000
INFO  | main | Created default XPathFactory com.sun.org.apache.xpath.internal.jaxp.XPathFactoryImpl@355a9bc3
INFO  | main | Route: route1 started and consuming from: Endpoint[file://src/test/data?noop=true]
INFO  | ActiveMQ Task-1 | Successfully connected to tcp://localhost:31313
INFO  | main | Route: route2 started and consuming from: Endpoint[activemq://personnel.records]
INFO  | main | Total 2 routes, of which 2 is started.
INFO  | main | Apache Camel 2.14.1 (CamelContext: camel-1) started in 0.343 seconds
INFO  | main | Root WebApplicationContext: initialization completed in 2140 ms
INFO  | main | Configuration will be discovered via JNDI
INFO  | main | Welcome to hawtio 1.5-SNAPSHOT : http://hawt.io/ : Don't cha wish your console was hawt like me? ;-)
INFO  | main | Using file upload directory: /var/folders/y5/2w4wn71500q3x4747r0g5bhm0000gn/T//uploads
2015-01-30 08:12:59.713:INFO:oejsh.ContextHandler:started o.m.j.p.JettyWebAppContext{/hawtio,[file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp/, file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/target/tmp/hawtio-default-1_5-SNAPSHOT_war/]},file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp/
2015-01-30 08:12:59.714:WARN:oejs.Holder:
java.lang.ClassNotFoundException: io.hawt.web.RedirectFilter
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
    at org.eclipse.jetty.util.Loader.loadClass(Loader.java:100)
    at org.eclipse.jetty.util.Loader.loadClass(Loader.java:79)
    at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:89)
    at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:79)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:707)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:254)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1238)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:689)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480)
    at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:256)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
    at org.eclipse.jetty.server.Server.doStart(Server.java:279)
    at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:520)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:365)
    at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:521)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-01-30 08:12:59.716:WARN:oejuc.AbstractLifeCycle:FAILED RedirectFilter: javax.servlet.UnavailableException: io.hawt.web.RedirectFilter
javax.servlet.UnavailableException: io.hawt.web.RedirectFilter
    at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:96)
    at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:79)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:707)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:254)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1238)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:689)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480)
    at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:256)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
    at org.eclipse.jetty.server.Server.doStart(Server.java:279)
    at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:520)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:365)
    at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:521)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-01-30 08:12:59.717:WARN:oejw.WebAppContext:Failed startup of context o.m.j.p.JettyWebAppContext{/hawtio,[file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp/, file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/target/tmp/hawtio-default-1_5-SNAPSHOT_war/]},file:/Users/chmoulli/Fuse/Fuse-projects/hawtio/sample/src/main/webapp/
javax.servlet.UnavailableException: io.hawt.web.RedirectFilter
    at org.eclipse.jetty.servlet.Holder.doStart(Holder.java:96)
    at org.eclipse.jetty.servlet.FilterHolder.doStart(FilterHolder.java:79)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:707)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:254)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1238)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:689)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480)
    at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:256)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
    at org.eclipse.jetty.server.Server.doStart(Server.java:279)
    at org.mortbay.jetty.plugin.JettyServer.doStart(JettyServer.java:65)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:520)
    at org.mortbay.jetty.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:365)
    at org.mortbay.jetty.plugin.JettyRunMojo.execute(JettyRunMojo.java:521)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-01-30 08:12:59.742:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8282
[INFO] Started Jetty Server
[INFO] Starting scanner at interval of 1 seconds.
```

**Comment by tadayosi** [comment]
Outdated.
