### ISSUE TITLE
Hawtio and Keycloak 1.6 integration

### ISSUE THREAD

**Issue by mcasperson** [hawtio/hawtio#2037]
When I attempt to log into Hawtio 1.4.56 configured to authenticate against KeyCloak 1.6 (using the instructions at https://github.com/hawtio/hawtio/blob/master/sample-keycloak-integration/README.md) I get the following errors:

```[Server:server-one] 03:29:25,851 WARN  [org.keycloak.protocol.oidc.endpoints.TokenEndpoint] (default task-15) Invoking deprecated endpoint http://111.111.111.111:8080/auth/realms/hawtio-demo/tokens/access/codes
[Server:server-one] WARN  | default task-8 | Login failed due org.keycloak.common.VerificationException: Realm URL is null. Make sure to add auth-server-url to the configuration of your adapter!
[Server:server-one] 03:29:29,498 WARN  [org.keycloak.protocol.oidc.endpoints.AuthorizationEndpoint] (default task-16) Invoking deprecated endpoint http://111.111.111.111:8080/auth/realms/hawtio-demo/tokens/login?client_id=hawtio-client&redirect_uri=http%3A%2F%2F54.66.248.252%3A8080%2Fconsole%2Flogin&state=9b6c710a-2331-4cfc-9e84-cf201118573b&response_type=code```

The error "Realm URL is null. Make sure to add auth-server-url to the configuration of your adapter!" seems to relate to a change that was made in Keycloak going from version 1.1 to 1.2 (http://keycloak.github.io/docs/userguide/keycloak-server/html/Migration_from_older_versions.html#d4e3653):

```The value of iss claim in access and id tokens have changed from realm name to realm url. This is required by OpenID Connect specification. If you're using our adapters there's no change required, other than if you've been using bearer-only without specifying auth-server-url you have to add it now. If you're using another library (or RSATokenVerifier) you need to make the corresponding changes when verifying iss. ```

Is there some trick to integrating Hawtio with KeyCloak 1.6?

**Comment by davsclaus** [comment]
@mposolda wonder if you have any idea?

**Comment by mposolda** [comment]
From the quick look, I think that it will help to add this line:

"auth-server-url" : "http://localhost:8081/auth",

to this file:
https://github.com/hawtio/hawtio/issues/2037#issuecomment-174171177
but didn't yet try it. 

I can try this week and can send PR with update to Keycloak 1.8. The originally used Keycloak 1.1 version is more than 1 year old. @davsclaus what do you think?

**Comment by davsclaus** [comment]
+1 

thanks

**Comment by kflorian** [comment]
Hi! Any news on this one?
I'm currently unsuccessful trying to get Hawtio to work with Keycloak 1.9.0.
Calling the old "/auth/realm/tokens/" APIs gives me an 404 error, not just a deprecation warning.
Output from the Keycloak server log:
> 11:37:55,101 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-27) RESTEASY002010: Failed to execute: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://server.company.com/auth/realms/hawtio/tokens/login?client_id=hawtio-client&redirect_uri=https%3A%2F%2Fserver.company.com%2Fhawtio%2F&state=6a0ef5cf-ae1e-44e1-8ae5-f5d3e81f2fee&response_type=code&response_mode=fragment
        at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:114)
        at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
        at org.jboss.resteasy.core.LocatorRegistry.getResourceInvoker(LocatorRegistry.java:79)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:129)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
        at org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:78)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Note that my realm is named "hawtio", not "hawtio-demo".
Updated documentation and samples for the current Keycloak version would be very much appreciated! 
thanks

**Comment by mposolda** [comment]
I will try to take a look on Friday/Monday and send PR to upgrade Keycloak to 1.9.1

**Comment by kflorian** [comment]
Thanks a lot!
At least the behavior I'm seeing seems to be expected for version 1.9.x: Citing from https://keycloak.github.io/docs/userguide/keycloak-server/html/Migration_from_older_versions.html#d4e4008

> Deprecated OpenID Connect endpoints
> In 1.2 we deprecated a number of endpoints that where not consistent with the OpenID Connect specifications, these have now been removed. This also applies to the validate token endpoints that was replaced with the new introspect endpoint in 1.8.

**Comment by kflorian** [comment]
I've just updated the keycloak version in hawtio-webapp/bower.json from 1.1.0 to 1.9.0, matching the keycloak library versions I'm using on the server.
Work's like a charm! :-)
I have just created a pull-request for the change, though you might want to update to 1.9.1 directly.

**Comment by kflorian** [comment]
Thanks for merging my PR! :-)
I think the issue is still valid, though, as the documentation in sample-keycloak-integration still needs updating: Hawtio will no longer be compatible with Keycloak version 1.1.0 that is mentioned in the README.

**Comment by davsclaus** [comment]
Ah thanks a PR to fix the readme file is much welcome

**Comment by kflorian** [comment]
PR pending...
