### ISSUE TITLE
Exception on rest commands that execute camel route operations if url pasted

### ISSUE THREAD

**Issue by dermoritz** [hawtio/hawtio#2046]
It seems similar to this: https://github.com/hawtio/hawtio/issues/1900

but this time i am using default camel route names. I tried it with different operations on "route1" e.g.:
* dumpRouteAsXml()
* getCamelId()

The exception occurs if i use "Copy Jolokia REST URL to clipboard" the url is
```
http://localhost:8081/hawtio/proxy/http://127.0.0.1:64182/jolokia//exec/org.apache.camel:context=camel-1,type=routes,name=%22route1%22/dumpRouteAsXml()
```

```
HTTP ERROR 500

Problem accessing /hawtio/proxy/http://127.0.0.1:64182/jolokia//exec/org.apache.camel:context=camel-1,type=routes,name=%22route1%22/dumpRouteAsXml(). Reason:

    Server Error
Caused by:

java.net.URISyntaxException: Illegal character in path at index 87: http://127.0.0.1:64182/jolokia//exec/org.apache.camel:context=camel-1,type=routes,name="route1"/dumpRouteAsXml()
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at io.hawt.web.ProxyServlet.service(ProxyServlet.java:181)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at io.hawt.web.CORSFilter.doFilter(CORSFilter.java:42)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at io.hawt.web.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:28)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at io.hawt.web.SessionExpiryFilter.process(SessionExpiryFilter.java:113)
	at io.hawt.web.SessionExpiryFilter.doFilter(SessionExpiryFilter.java:57)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Powered by Jetty://
```
The commands are executed fine via "execute" button

**Comment by davsclaus** [comment]
Similar error as #2063

**Comment by davsclaus** [comment]
btw what version of hawtio are you using?

**Comment by davsclaus** [comment]
Should be fixed now
