### ISSUE TITLE
Linkage error when trying to run hawtio with plugins

### ISSUE THREAD

**Issue by ozsaffer** [hawtio/hawtio#2053]
Hi,

I have just downloaded hawtio-app-1.59.jar and hawtio-web-1.4.59.war. I have placed the .jar in a folder and the .war in a plugin folder. 

However when I run the app I get a Linkage error(below). The app does start and I am able to browse the web console, but I am not sure if the plugin bundle is installed. 

Any help would be appreciated.

localhost:hawtio andre$ java -jar hawtio-app-1.4.59.jar -pd ~/Documents/Vita/hawtio/
[main] INFO jetty - using temp directory for jetty: /Users/andre/.hawtio/tmp
[main] INFO jetty - Scanning for 3rd party plugins in directory: hawtio
[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /hawtio-web-1.4.59, did not find org.apache.jasper.servlet.JspServlet
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext{/hawtio-web-1.4.59,file:/Users/andre/.hawtio/tmp/hawtio-web-1.4.59.war/webapp/},file:///Users/andre/Documents/Vita/hawtio/hawtio-web-1.4.59.war
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:367)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1240)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.findThirdPartyPlugins(Main.java:179)
	at io.hawt.embedded.Main.run(Main.java:108)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type LoggerFactory; used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:335)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
	at io.hawt.jmx.JmxTreeWatcher.<clinit>(JmxTreeWatcher.java:24)
	at io.hawt.HawtioContextListener.<init>(HawtioContextListener.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createListener(ContextHandler.java:2375)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createListener(ServletContextHandler.java:1227)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:1937)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1894)
	... 15 more
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED o.e.j.w.WebAppContext{/hawtio-web-1.4.59,file:/Users/andre/.hawtio/tmp/hawtio-web-1.4.59.war/webapp/},file:///Users/andre/Documents/Vita/hawtio/hawtio-web-1.4.59.war: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:367)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1240)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.findThirdPartyPlugins(Main.java:179)
	at io.hawt.embedded.Main.run(Main.java:108)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type LoggerFactory; used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:335)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
	at io.hawt.jmx.JmxTreeWatcher.<clinit>(JmxTreeWatcher.java:24)
	at io.hawt.HawtioContextListener.<init>(HawtioContextListener.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createListener(ContextHandler.java:2375)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createListener(ServletContextHandler.java:1227)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:1937)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1894)
	... 15 more
[main] WARN jetty - Failed to add and start 3rd party plugin with context-path: /hawtio-web-1.4.59 due null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:367)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1240)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.findThirdPartyPlugins(Main.java:179)
	at io.hawt.embedded.Main.run(Main.java:108)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for resolved class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type LoggerFactory; used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:335)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
	at io.hawt.jmx.JmxTreeWatcher.<clinit>(JmxTreeWatcher.java:24)
	at io.hawt.HawtioContextListener.<init>(HawtioContextListener.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createListener(ContextHandler.java:2375)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createListener(ServletContextHandler.java:1227)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:1937)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1894)
	... 15 more
Embedded hawtio: You can use --help to show usage
Using options [
	war=/private/var/folders/f2/89zj984n2jx7z2ny9h5_d2f00000gn/T/hawtio-6265018710522595565.war
	contextPath=/hawtio
	port=8080
	extraClassPath=file:/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/lib/tools.jar
	plugins=/Users/andre/Documents/Vita/hawtio/
	jointServerThread=false
	help=false]
About to start hawtio /private/var/folders/f2/89zj984n2jx7z2ny9h5_d2f00000gn/T/hawtio-6265018710522595565.war
[main] INFO org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT
[main] INFO org.eclipse.jetty.webapp.WebInfConfiguration - Extract jar:file:/private/var/folders/f2/89zj984n2jx7z2ny9h5_d2f00000gn/T/hawtio-6265018710522595565.war!/ to /Users/andre/.hawtio/tmp/webapp
[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /hawtio, did not find org.apache.jasper.servlet.JspServlet
[main] INFO io.hawt.system.ConfigManager - Configuration will be discovered via system properties
[main] INFO io.hawt.jmx.JmxTreeWatcher - Welcome to hawtio 1.4.59 : http://hawt.io/ : Don't cha wish your console was hawt like me? ;-)
[main] INFO io.hawt.jmx.UploadManager - Using file upload directory: /var/folders/f2/89zj984n2jx7z2ny9h5_d2f00000gn/T//uploads
[main] INFO /hawtio - Loading Blueprint contexts [file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/classes/OSGI-INF/blueprint/blueprint.xml, jar:file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-aether-1.4.59.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-core-1.4.59.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-git-1.4.59.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-ide-1.4.59.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-json-schema-mbean-1.4.59.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/Users/andre/.hawtio/tmp/webapp/WEB-INF/lib/hawtio-local-jvm-mbean-1.4.59.jar!/OSGI-INF/blueprint/blueprint.xml]
[main] INFO io.hawt.log.log4j.Log4jLogQuery - Connected to Log4j appender to trap logs with hawtio log plugin
[main] INFO io.hawt.git.GitFacade - hawtio using config directory: /Users/andre/.hawtio/config
[main] INFO io.hawt.git.GitFacade - Performing a pull in git repository /Users/andre/.hawtio/config on remote URL: https://github.com/hawtio/hawtio-config.git. Subsequent pull attempts will use debug logging
[main] INFO io.hawt.web.AuthenticationFilter - Starting hawtio authentication filter, JAAS authentication disabled
[main] INFO /hawtio - jolokia-agent: Using access restrictor classpath:/jolokia-access.xml
[main] INFO org.eclipse.jetty.webapp.WebAppContext - hawtio at http://0.0.0.0:8080/hawtio
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:8080

hawtio: Don't cha wish your console was hawt like me!
=====================================================

http://localhost:8080/hawtio

[qtp1707345075-25] INFO io.hawt.web.keycloak.KeycloakServlet - Keycloak integration is disabled

**Comment by davsclaus** [comment]
You should not put hawtio itself in the plugins directory, that is only for custom 3rd party plugins you build. Just start it according to documentation with just java -jar or drop the .war in tomcat etc for war deployments.
