### ISSUE TITLE
App with plugins on Windows

### ISSUE THREAD

**Issue by a-belevich** [hawtio/hawtio#2061]
I'm trying to use `hawtio-app-1.4.59.jar` with a plugin (inside `plugins` folder) on Windows. App throws an `UnknownHostException` exception (see below). It happens because setting `war` path as ```plugin.setWar("file://" + war.getAbsolutePath());``` in `hawtio-embedded/src/main/java/io/hawt/embedded/Main.java` on Windows leads to URL like `file://C:\Users\...`. Changing the line to ```plugin.setWar(war.getAbsolutePath());``` solves the problem.

The exception is:

[main] INFO jetty - Scanning for 3rd party plugins in directory: plugins
[main] INFO org.eclipse.jetty.webapp.WebInfConfiguration - Extract jar:file://C:
/work/tools/hawt.io/run/plugins/eureka-client-plugin.war!/ to C:\Users\a.belevic
h\.hawtio\tmp\eureka-client-plugin.war\webapp
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o
.e.j.w.WebAppContext{/eureka-client-plugin,null},file://C:\work\tools\hawt.io\ru
n\plugins\eureka-client-plugin.war
java.net.UnknownHostException: C
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.doConnect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.tryConnect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
        at sun.net.www.protocol.ftp.FtpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(Unknown Sour
ce)
        at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:1
56)
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:480)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:71)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:457)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at io.hawt.embedded.Main.findThirdPartyPlugins(Main.java:179)
        at io.hawt.embedded.Main.run(Main.java:108)
        at io.hawt.embedded.Main.run(Main.java:70)
        at io.hawt.app.App.main(App.java:101)
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED o.e.j.w.
WebAppContext{/eureka-client-plugin,null},file://C:\work\tools\hawt.io\run\plugi
ns\eureka-client-plugin.war: java.net.UnknownHostException: C
java.net.UnknownHostException: C
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.doConnect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.tryConnect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
        at sun.net.www.protocol.ftp.FtpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(Unknown Sour
ce)
        at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:1
56)
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:480)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:71)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:457)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at io.hawt.embedded.Main.findThirdPartyPlugins(Main.java:179)
        at io.hawt.embedded.Main.run(Main.java:108)
        at io.hawt.embedded.Main.run(Main.java:70)
        at io.hawt.app.App.main(App.java:101)
[main] WARN jetty - Failed to add and start 3rd party plugin with context-path:
/eureka-client-plugin due C
java.net.UnknownHostException: C
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.doConnect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.tryConnect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
        at sun.net.ftp.impl.FtpClient.connect(Unknown Source)
        at sun.net.www.protocol.ftp.FtpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(Unknown Sour
ce)
        at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:1
56)
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:480)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:71)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:457)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:493
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at io.hawt.embedded.Main.findThirdPartyPlugins(Main.java:179)
        at io.hawt.embedded.Main.run(Main.java:108)
        at io.hawt.embedded.Main.run(Main.java:70)
        at io.hawt.app.App.main(App.java:101)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.y.z-SNAPSHOT

**Comment by davsclaus** [comment]
Thanks for reporting.
