### ISSUE TITLE
Camel plugin - Send to endpoint fails

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2063]
It seems that sending to file / activemq endpoints fails with. Cannot send to this endpoint.

![screen shot 2016-01-11 at 2 50 37 pm](https://cloud.githubusercontent.com/assets/477100/12235241/c20ab732-b872-11e5-9984-239c2d7fcc53.png)

**Comment by davsclaus** [comment]
Found this stacktrace
```
[qtp517380410-19] WARN org.eclipse.jetty.servlet.ServletHandler - /hawtio/proxy/http://127.0.0.1:54155/jolokia//exec/org.apache.camel%3Acontext%3Dcamel-1%2Ctype%3Dcontext%2Cname%3D%22camel-1%22/canSendToEndpoint(java.lang.String)/activemq%3A!%2F!%2Fqueue%3AnewOrder
java.net.URISyntaxException: Illegal character in path at index 88: http://127.0.0.1:54155/jolokia//exec/org.apache.camel:context=camel-1,type=context,name="camel-1"/canSendToEndpoint(java.lang.String)/activemq:!/!/queue:newOrder?maxDepth=7&maxCollectionSize=5000&ignoreErrors=true&canonicalNaming=false
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at io.hawt.web.ProxyServlet.service(ProxyServlet.java:181)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
	at io.hawt.web.CORSFilter.doFilter(CORSFilter.java:42)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at io.hawt.web.XFrameOptionsFilter.doFilter(XFrameOptionsFilter.java:28)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1484)
	at io.hawt.web.SessionExpiryFilter.process(SessionExpiryFilter.java:113)
	at io.hawt.web.SessionExpiryFilter.doFilter(SessionExpiryFilter.java:57)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by alhafoudh** [comment]
+1

**Comment by davsclaus** [comment]
The invalid uri is the quotes in the camel context name, eg `name="camel-1"`

**Comment by davsclaus** [comment]
I wonder if we changed some code in the proxy servlet. We got some PRs to improve security stuff.

**Comment by davsclaus** [comment]
This only happens when you proxy to a remote jvm

**Comment by davsclaus** [comment]
1.
Start a JVM with Camel running such as JBoss Fuse and have a Camel application deployed

2.
Start hawtio in another JVM such as hawtio-app with `java -jar`
http://hawt.io/getstarted/index.html

3.
And then use the Connector plugin in hawtio, and connect using `remote` to that other JVM. You will need to type in the port number, context path, and maybe login as well, which can be tricky on JBoss Fuse, and also to find that jolokia path, which is something like `api/jolokia` or something.

4.
Browse the Camel and find endpoints, and try to send message to it. You can create an endpoint first such as `seda:foo` and then send messages to that endpoint.
