### ISSUE TITLE
hawtio 1.4.60 cannot install on servicemix 6.0.2

### ISSUE THREAD

**Issue by twalzer** [hawtio/hawtio#2086]
Here is what I did:
----
feature:repo-add hawtio 1.4.60
feature:install hawtio

here is what happened:
----
2016-02-03 16:22:09,984 | ERROR | l for user karaf | ShellUtil                        | 27 - org.apache.karaf.shell.console - 3.0.5 | Exception caught while executing command
java.lang.IllegalStateException: Can't install feature hawtio/0.0.0:
Can not resolve feature:
Unsatisfied requirement(s):
---------------------------
   package:(&(package=org.apache.karaf.shell.console)(version>=4.0.0)(!(version>=5.0.0)))
      hawtio :: Karaf terminal plugin

	at org.apache.karaf.features.internal.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:405)
	at Proxy862b4211_dace_40d7_8a48_64d060fc5f75.installFeature(Unknown Source)
	at org.apache.karaf.features.command.InstallFeatureCommand.doExecute(InstallFeatureCommand.java:72)
	at org.apache.karaf.features.command.FeaturesCommandSupport.doExecute(FeaturesCommandSupport.java:38)
	at org.apache.karaf.shell.console.AbstractAction.execute(AbstractAction.java:33)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.karaf.shell.console.OsgiCommandSupport.execute(OsgiCommandSupport.java:39)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.karaf.shell.commands.basic.AbstractCommand.execute(AbstractCommand.java:33)[27:org.apache.karaf.shell.console:3.0.5]
	at Proxy8a318cd2_0bce_4b92_b831_1aefcd659c42.execute(Unknown Source)[:]
	at Proxy8a318cd2_0bce_4b92_b831_1aefcd659c42.execute(Unknown Source)[:]
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:78)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:480)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:406)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.felix.gogo.runtime.Pipe.run(Pipe.java:108)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:182)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:119)[27:org.apache.karaf.shell.console:3.0.5]
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:94)
	at org.apache.karaf.shell.console.impl.jline.ConsoleImpl.run(ConsoleImpl.java:210)
	at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1$1.run(LocalConsoleManager.java:109)
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_31]
	at org.apache.karaf.jaas.modules.JaasHelper.doAs(JaasHelper.java:57)[28:org.apache.karaf.jaas.modules:3.0.5]
	at org.apache.karaf.shell.console.impl.jline.LocalConsoleManager$2$1.run(LocalConsoleManager.java:102)[27:org.apache.karaf.shell.console:3.0.5]

here is my setup
----
karaf@root>info
Karaf
  Karaf version               3.0.5
  Karaf home                  /Users/thomas/apache-servicemix-6.0.2
  Karaf base                  /Users/thomas/apache-servicemix-6.0.2
  Karaf etc                   /Users/thomas/apache-servicemix-6.0.2/etc
  OSGi Framework              org.apache.felix.framework - 4.2.1

JVM
  Java Virtual Machine        Java HotSpot(TM) 64-Bit Server VM version 25.31-b07
  Version                     1.8.0_31
  Vendor                      Oracle Corporation
  Pid                         3517
  Uptime                      4 minutes
  Total compile time          29.381 seconds
Threads
  Live threads                70
  Daemon threads              57
  Peak                        72
  Total started               84
Memory
  Current heap size           114,444 kbytes
  Maximum heap size           466,432 kbytes
  Committed heap size         264,192 kbytes
  Pending objects             0
  Garbage collector           Name = 'PS Scavenge', Collections = 17, Time = 0.617 seconds
  Garbage collector           Name = 'PS MarkSweep', Collections = 2, Time = 0.600 seconds
Classes
  Current classes loaded      7,894
  Total classes loaded        7,895
  Total classes unloaded      1
Operating system
  Name                        Mac OS X version 10.11.2
  Architecture                x86_64
  Processors                  2

Cheers, Thomas.

**Comment by davsclaus** [comment]
Ah try with install hawtio-core, to avoid installing the terminal console

**Comment by twalzer** [comment]
Works like a charm. Thank you, Claus.
May I suggest a sentence to be added to the getting-started:

If running on Servicemix 6.x or on Karaf > 3.0 there are problems with the terminal console. So to install it there use:
`feature:repo-add hawtio 1.4.60`
`feature:install hawtio-core`

Cheers, Thomas.

**Comment by davsclaus** [comment]
Yeah @twalzer that is a good idea, I just added a note to the docs.

**Comment by davsclaus** [comment]
btw this ticket is about the terminal issue
https://github.com/hawtio/hawtio/issues/2028
