### ISSUE TITLE
Deploying issue under Weblogic 12.1.1 when I tried to activate the authentication

### ISSUE THREAD

**Issue by curso007** [hawtio/hawtio#2094]
Dears,

I tried to enable authentication of  Hawtio war version 1.61.2 and deploy it on Weblogic (12.1.1).
You guessed that it failed. 
I got this:

```
### <26-Feb-2016 17:44:18 o'clock CET> <Error> <HTTP> <BEA-101020> <[ServletContext@1884254248[app:_appsdir_SHawtio_war module:SHawtio.war path:null spec-version:3.0]] Servlet failed with an Exception
java.lang.IllegalArgumentException: No Configuration was registered that can handle the configuration named myrealm
	at com.bea.common.security.jdkutils.JAASConfiguration.getAppConfigurationEntry(JAASConfiguration.java:130)
	at javax.security.auth.login.LoginContext.init(LoginContext.java:259)
	at javax.security.auth.login.LoginContext.<init>(LoginContext.java:389)
	at javax.security.auth.login.LoginContext.<init>(LoginContext.java:466)
	at io.hawt.system.Authenticator.doAuthenticate(Authenticator.java:119)
	Truncated. see log file for complete stacktrace
> 
```

Here the update I did in the web.xml:

```
  <env-entry>
    <description>Enable/disable hawtio's authentication filter, value is really a boolean</description>
    <env-entry-name>hawtio/authenticationEnabled</env-entry-name>
    <env-entry-type>java.lang.String</env-entry-type>
    <env-entry-value>true</env-entry-value>
  </env-entry>
  <env-entry>
    <description>Authorized user role, empty string disables authorization</description>
    <env-entry-name>hawtio/role</env-entry-name>
    <env-entry-type>java.lang.String</env-entry-type>
    <env-entry-value>admin,viewer</env-entry-value>
  </env-entry>
  <env-entry>
    <description>JAAS realm used to authenticate users</description>
    <env-entry-name>hawtio/realm</env-entry-name>
    <env-entry-type>java.lang.String</env-entry-type>
    <env-entry-value>**myrealm**</env-entry-value>
  </env-entry>
```

here is the content of the weblogic.xml I injected next to the web.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<weblogic-web-app xmlns="http://xmlns.oracle.com/weblogic/weblogic-web-app" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd http://xmlns.oracle.com/weblogic/weblogic-web-app http://xmlns.oracle.com/weblogic/weblogic-web-app/1.2/weblogic-web-app.xsd">

	<security-role-assignment>
		<role-name>admin</role-name>
		<principal-name>ursouca</principal-name>
	</security-role-assignment>
	
	<security-role-assignment>
		<role-name>viewer</role-name>
		<principal-name>ursouca</principal-name>
	</security-role-assignment>
</weblogic-web-app>

```

How I have to configure to make it work? 
Do I have to provide an authenticationContainerDiscoveryClasses class that supports JEE security or Weblogic specific one?

Thanks in advance for your help.

**Comment by gashcrumb** [comment]
The hawtio authenticator only works with JAAS, so you'd need to set up the appropriate JAAS configuration, think the exception is indicating that the code can't fine one.  Took a quick scan of the weblogic docs, but didn't see an obvious code snippet I could link you to.  Good luck!
