### ISSUE TITLE
Unable to run hawtio-web locally with mvn test-compile exec:java command

### ISSUE THREAD

**Issue by oscerd** [hawtio/hawtio#2154]
```shell
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hawtio-web ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ hawtio-web ---
WARN  | io.hawt.sample.Main.main() | Could not start network bridge between: vm://broker1?async=false and: tcp://localhost:31317 due to: Connection refused
WARN  | JMX connector | Failed to start JMX connector Cannot bind to URL [rmi://localhost:1099/jmxrmi]: javax.naming.NameAlreadyBoundException: jmxrmi [Root exception is java.rmi.AlreadyBoundException: jmxrmi]. Will restart management to re-create JMX connector, trying to remedy this issue.
WARN  | JMX connector | Failed to start JMX connector Cannot bind to URL [rmi://localhost:1099/jmxrmi]: javax.naming.NameAlreadyBoundException: jmxrmi [Root exception is java.rmi.AlreadyBoundException: jmxrmi]. Will restart management to re-create JMX connector, trying to remedy this issue.
WARN  | io.hawt.sample.Main.main() | ISPN000176: The 'wakeUpInterval' attribute of the 'eviction' configuration XML element is deprecated. Setting the 'wakeUpInterval' attribute of the 'expiration' configuration XML element to 100 instead
WARN  | io.hawt.sample.Main.main() | Don't run with scissors!
ERROR | io.hawt.sample.Main.main() | Someone somewhere is not using Fuse! :)
org.apache.camel.CamelException: My exception message
	at io.hawt.sample.Main.main(Main.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
ERROR | io.hawt.sample.Main.main() | Expected exception for testing: java.lang.NullPointerException
java.lang.NullPointerException
	at org.apache.camel.util.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:79)
	at io.hawt.sample.Main.main(Main.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)


OPEN: http://localhost:8282/hawtio using web app source path: [jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-core/1.5-SNAPSHOT/hawtio-core-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-git/1.5-SNAPSHOT/hawtio-git-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-junit/1.5-SNAPSHOT/hawtio-junit-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-json-schema-mbean/1.5-SNAPSHOT/hawtio-json-schema-mbean-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-local-jvm-mbean/1.5-SNAPSHOT/hawtio-local-jvm-mbean-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-keystore-mbean/1.5-SNAPSHOT/hawtio-keystore-mbean-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-aether/1.5-SNAPSHOT/hawtio-aether-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml, jar:file:/home/oscerd/.m2/repository/io/hawt/hawtio-dozer/1.5-SNAPSHOT/hawtio-dozer-1.5-SNAPSHOT.jar!/OSGI-INF/blueprint/blueprint.xml]


INFO  | io.hawt.sample.Main.main() | Configuration will be discovered via system properties
WARN  | io.hawt.sample.Main.main() | unavailable
java.lang.IllegalArgumentException: No custom restrictor class io.hawt.web.RBACRestrictor found
	at org.jolokia.restrictor.RestrictorFactory.createCustomRestrictor(RestrictorFactory.java:71)
	at org.jolokia.restrictor.RestrictorFactory.createRestrictor(RestrictorFactory.java:41)
	at org.jolokia.http.AgentServlet.init(AgentServlet.java:130)
	at io.hawt.web.JolokiaConfiguredAgentServlet.init(JolokiaConfiguredAgentServlet.java:44)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.sample.Main.main(Main.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
WARN  | io.hawt.sample.Main.main() | FAILED jolokia-agent: javax.servlet.ServletException: jolokia-agent
javax.servlet.ServletException: jolokia-agent
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:553)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.sample.Main.main(Main.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No custom restrictor class io.hawt.web.RBACRestrictor found
	at org.jolokia.restrictor.RestrictorFactory.createCustomRestrictor(RestrictorFactory.java:71)
	at org.jolokia.restrictor.RestrictorFactory.createRestrictor(RestrictorFactory.java:41)
	at org.jolokia.http.AgentServlet.init(AgentServlet.java:130)
	at io.hawt.web.JolokiaConfiguredAgentServlet.init(JolokiaConfiguredAgentServlet.java:44)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	... 19 more
WARN  | io.hawt.sample.Main.main() | Failed startup of context o.m.j.p.JettyWebAppContext{/hawtio,[file:/home/oscerd/workspace/miscellanea/hawtio/hawtio-web/src/main/webapp/]}
javax.servlet.ServletException: jolokia-agent
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:553)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.mortbay.jetty.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:298)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.sample.Main.main(Main.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: No custom restrictor class io.hawt.web.RBACRestrictor found
	at org.jolokia.restrictor.RestrictorFactory.createCustomRestrictor(RestrictorFactory.java:71)
	at org.jolokia.restrictor.RestrictorFactory.createRestrictor(RestrictorFactory.java:41)
	at org.jolokia.http.AgentServlet.init(AgentServlet.java:130)
	at io.hawt.web.JolokiaConfiguredAgentServlet.init(JolokiaConfiguredAgentServlet.java:44)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	... 19 more
Caught unexpected exception: java.io.IOException: User limit of inotify watches reached

java.io.IOException: User limit of inotify watches reached
	at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
	at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
	at java.lang.Thread.run(Thread.java:745)
ERROR | io.hawt.sample.Main.main() | 
java.lang.NullPointerException
	at net_alchim31_livereload.LRServer.stop(LRServer.java:100)
	at net_alchim31_livereload.LRServer.run(LRServer.java:91)
	at io.hawt.sample.Main.main(Main.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
```

Usually when you run this command, you get some exception but it works and you're able to see hawtio running.

What it's new now is this part:

_java.lang.IllegalArgumentException: No custom restrictor class io.hawt.web.RBACRestrictor found_

I believe this is related to this commit

https://github.com/hawtio/hawtio/commit/bb27b3321e4e3e974ad8a05685207320f7fe09e8

**Comment by oscerd** [comment]
My mistake. It's ok :-)

Closing :-)

**Comment by tadayosi** [comment]
Yeah, probably you've needed to run `mvn install` for `hawtio-system` first ;-)

**Comment by oscerd** [comment]
Absolutely :-)

I was too fast to open an issue ;-)
