### ISSUE TITLE
hawtio-git - Unit test fails

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2167]
I run with JAVA7 with latest code. I just run `mvn clean install` from the root of the project and now it fails at
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.hawt.git.GitBranchDiffTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.556 sec <<< FAILURE! - in io.hawt.git.GitBranchDiffTest
testBranchesAndDiff(io.hawt.git.GitBranchDiffTest)  Time elapsed: 0.323 sec  <<< ERROR!
org.eclipse.jgit.api.errors.JGitInternalException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitBranchDiffTest.init(GitBranchDiffTest.java:44)
Caused by: java.io.IOException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitBranchDiffTest.init(GitBranchDiffTest.java:44)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitBranchDiffTest.init(GitBranchDiffTest.java:44)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Invalid included path in config file: ~/.gitcinclude
	at io.hawt.git.GitBranchDiffTest.init(GitBranchDiffTest.java:44)

Running io.hawt.git.GitCloneTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.027 sec <<< FAILURE! - in io.hawt.git.GitCloneTest
clonedRemoteRepo(io.hawt.git.GitCloneTest)  Time elapsed: 0.027 sec  <<< ERROR!
org.eclipse.jgit.api.errors.JGitInternalException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitCloneTest.init(GitCloneTest.java:19)
Caused by: java.io.IOException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitCloneTest.init(GitCloneTest.java:19)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitCloneTest.init(GitCloneTest.java:19)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Invalid included path in config file: ~/.gitcinclude
	at io.hawt.git.GitCloneTest.init(GitCloneTest.java:19)

Running io.hawt.git.GitFacadeTest
Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 0.015 sec <<< FAILURE! - in io.hawt.git.GitFacadeTest
testExists(io.hawt.git.GitFacadeTest)  Time elapsed: 0.004 sec  <<< ERROR!
org.eclipse.jgit.api.errors.JGitInternalException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitFacadeTest.init(GitFacadeTest.java:70)
Caused by: java.io.IOException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitFacadeTest.init(GitFacadeTest.java:70)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.git.GitFacadeTest.init(GitFacadeTest.java:70)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Invalid included path in config file: ~/.gitcinclude
	at io.hawt.git.GitFacadeTest.init(GitFacadeTest.java:70)

Running io.hawt.git.VersionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.hawt.git.VersionTest
Running io.hawt.io.FileFilterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec - in io.hawt.io.FileFilterTest

Results :

Tests in error:
  GitBranchDiffTest.init:44 » JGitInternal Systen wide config file /usr/local/gi...
  GitCloneTest.init:19 » JGitInternal Systen wide config file /usr/local/git/etc...
  GitFacadeTest.init:70 » JGitInternal Systen wide config file /usr/local/git/et...

Tests run: 6, Failures: 0, Errors: 3, Skipped: 1

```

**Comment by davsclaus** [comment]
@oscerd wonder if you have seen this kind of error? And if its related to jgit upgrades?

**Comment by davsclaus** [comment]
There is also test failures in `hawtio-system` module

```
Running io.hawt.jmx.JmxTreeWatcherTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.738 sec <<< FAILURE! - in io.hawt.jmx.JmxTreeWatcherTest
testNotificationsOnNewMBeans(io.hawt.jmx.JmxTreeWatcherTest)  Time elapsed: 0.549 sec  <<< ERROR!
java.io.IOException: Systen wide config file /usr/local/git/etc/gitconfig is invalid org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.jmx.JmxTreeWatcherTest.testNotificationsOnNewMBeans(JmxTreeWatcherTest.java:30)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Cannot read file /usr/local/git/etc/gitconfig
	at io.hawt.jmx.JmxTreeWatcherTest.testNotificationsOnNewMBeans(JmxTreeWatcherTest.java:30)
Caused by: org.eclipse.jgit.errors.ConfigInvalidException: Invalid included path in config file: ~/.gitcinclude
	at io.hawt.jmx.JmxTreeWatcherTest.testNotificationsOnNewMBeans(JmxTreeWatcherTest.java:30)
```

**Comment by davsclaus** [comment]
If I revert this commit then those unit tests now passes
https://github.com/hawtio/hawtio/commit/3a576bebdbcb20ba8c5de0c08fafaa36b57de0ce

**Comment by davsclaus** [comment]
I reverted the commit to make the code pass the test again.

**Comment by oscerd** [comment]
Maybe the new JGit is only Java8 and I compiled hawtio with Java8 I guess.

Let me check.

**Comment by oscerd** [comment]
Locally It works with Java7.

```shell
oscerd@localhost:~/workspace/miscellanea/hawtio/hawtio-git$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0_79/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.18.2.el7.x86_64", arch: "amd64", family: "unix"
oscerd@localhost:~/workspace/miscellanea/hawtio/hawtio-git$ mvn clean install
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] 'profiles.profile.id' must be unique but found duplicate profile with id jboss-public-repository @ /opt/apache-maven-3.3.9/conf/settings.xml
[WARNING] 'profiles.profile.id' must be unique but found duplicate profile with id redhat-earlyaccess-repository @ /opt/apache-maven-3.3.9/conf/settings.xml
[WARNING] 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hawtio-git 1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hawtio-git ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-git ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-git ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-git ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-git ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /home/oscerd/workspace/miscellanea/hawtio/hawtio-git && git rev-parse --verify HEAD
[INFO] Working directory: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git
[INFO] Storing buildNumber: bb7258016b8467f0190deaf00a17bd5083729c72 at timestamp: 1467353742524
[INFO] Executing: /bin/sh -c cd /home/oscerd/workspace/miscellanea/hawtio/hawtio-git && git rev-parse --verify HEAD
[INFO] Working directory: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hawtio-git ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hawtio-git ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/classes
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/src/main/java/io/hawt/git/GitFacadeSupport.java: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/src/main/java/io/hawt/git/GitFacadeSupport.java uses unchecked or unsafe operations.
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/src/main/java/io/hawt/git/GitFacadeSupport.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:manifest (bundle-manifest) @ hawtio-git ---
[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Instructions in Export-Package that are never used: javaewah.*
Classpath: Jar:.,Jar:servlet-api,Jar:slf4j-api,Jar:hawtio-core,Jar:hawtio-util,Jar:org.eclipse.jgit,Jar:jsch,Jar:JavaEWAH,Jar:httpclient,Jar:httpcore,Jar:commons-logging,Jar:commons-codec,Jar:gitective-core,Jar:jzlib

[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Superfluous export-package instructions: [javaewah*]
[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for !keypairgen
[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for !signature
[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for !userauth
[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for javaewah*
[WARNING] Manifest io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for org.gitective*
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hawtio-git ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hawtio-git ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ hawtio-git ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.hawt.git.GitBranchDiffTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.437 sec - in io.hawt.git.GitBranchDiffTest
Running io.hawt.git.GitCloneTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.142 sec - in io.hawt.git.GitCloneTest
Running io.hawt.git.GitFacadeTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.044 sec - in io.hawt.git.GitFacadeTest
Running io.hawt.git.VersionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.hawt.git.VersionTest
Running io.hawt.io.FileFilterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.hawt.io.FileFilterTest

Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 1

[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:bundle (default-bundle) @ hawtio-git ---
[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Instructions in Export-Package that are never used: javaewah.*
Classpath: Jar:.,Jar:servlet-api,Jar:slf4j-api,Jar:hawtio-core,Jar:hawtio-util,Jar:org.eclipse.jgit,Jar:jsch,Jar:JavaEWAH,Jar:httpclient,Jar:httpcore,Jar:commons-logging,Jar:commons-codec,Jar:gitective-core,Jar:jzlib

[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Superfluous export-package instructions: [javaewah*]
[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for !keypairgen
[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for !signature
[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for !userauth
[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for javaewah*
[WARNING] Bundle io.hawt:hawtio-git:bundle:1.5-SNAPSHOT : Did not find matching referal for org.gitective*
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar-no-fork (attach-sources) @ hawtio-git ---
[INFO] Building jar: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT-sources.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ hawtio-git >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-git ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-git ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-git ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-git ---
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ hawtio-git <<<
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ hawtio-git ---
[INFO] 
[INFO] --- unsigner-maven-plugin:0.2:unsign (unsign-jar) @ hawtio-git ---
[INFO] Unsigning project artifact: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT.jar
Jul 01, 2016 8:15:49 AM org.commonjava.maven.plugin.unsigner.Unsigner unsign
INFO: Backing up original jar: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT.jar
    to: /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT.jar.bak
[INFO] Unsigned 1 jars.
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hawtio-git ---
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT.jar to /home/oscerd/.m2/repository/io/hawt/hawtio-git/1.5-SNAPSHOT/hawtio-git-1.5-SNAPSHOT.jar
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/pom.xml to /home/oscerd/.m2/repository/io/hawt/hawtio-git/1.5-SNAPSHOT/hawtio-git-1.5-SNAPSHOT.pom
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT-sources.jar to /home/oscerd/.m2/repository/io/hawt/hawtio-git/1.5-SNAPSHOT/hawtio-git-1.5-SNAPSHOT-sources.jar
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-git/target/hawtio-git-1.5-SNAPSHOT-sources.jar to /home/oscerd/.m2/repository/io/hawt/hawtio-git/1.5-SNAPSHOT/hawtio-git-1.5-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- maven-bundle-plugin:2.3.7:install (default-install) @ hawtio-git ---
[INFO] Installing io/hawt/hawtio-git/1.5-SNAPSHOT/hawtio-git-1.5-SNAPSHOT.jar
[INFO] Writing OBR metadata
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.442 s
[INFO] Finished at: 2016-07-01T08:15:51+02:00
[INFO] Final Memory: 45M/974M
[INFO] ------------------------------------------------------------------------
```

and hawtio-system too

```shell
oscerd@localhost:~/workspace/miscellanea/hawtio/hawtio-system$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.7.0_79/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.18.2.el7.x86_64", arch: "amd64", family: "unix"
oscerd@localhost:~/workspace/miscellanea/hawtio/hawtio-system$ mvn clean install
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] 'profiles.profile.id' must be unique but found duplicate profile with id jboss-public-repository @ /opt/apache-maven-3.3.9/conf/settings.xml
[WARNING] 'profiles.profile.id' must be unique but found duplicate profile with id redhat-earlyaccess-repository @ /opt/apache-maven-3.3.9/conf/settings.xml
[WARNING] 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hawtio-system 1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hawtio-system ---
[INFO] Deleting /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-system ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-system ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-system ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-system ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /home/oscerd/workspace/miscellanea/hawtio/hawtio-system && git rev-parse --verify HEAD
[INFO] Working directory: /home/oscerd/workspace/miscellanea/hawtio/hawtio-system
[INFO] Storing buildNumber: bb7258016b8467f0190deaf00a17bd5083729c72 at timestamp: 1467353808051
[INFO] Executing: /bin/sh -c cd /home/oscerd/workspace/miscellanea/hawtio/hawtio-system && git rev-parse --verify HEAD
[INFO] Working directory: /home/oscerd/workspace/miscellanea/hawtio/hawtio-system
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hawtio-system ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ hawtio-system ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 57 source files to /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/classes
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/ProxyServlet.java:[7,38] org.apache.http.client.methods.AbortableHttpRequest in org.apache.http.client.methods has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/ProxyServlet.java:[15,35] org.apache.http.impl.client.DefaultHttpClient in org.apache.http.impl.client has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/ProxyServlet.java:[250,28] setStatus(int,java.lang.String) in javax.servlet.http.HttpServletResponse has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/ProxyServlet.java:[259,41] org.apache.http.client.methods.AbortableHttpRequest in org.apache.http.client.methods has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/ProxyServlet.java:[260,17] org.apache.http.client.methods.AbortableHttpRequest in org.apache.http.client.methods has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/ProxyServlet.java:[260,62] org.apache.http.client.methods.AbortableHttpRequest in org.apache.http.client.methods has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/web/tomcat/TomcatUserDatabaseLoginContext.java:[74,77] shaHex(java.lang.String) in org.apache.commons.codec.digest.DigestUtils has been deprecated
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/jmx/QuartzFacade.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/src/main/java/io/hawt/jmx/QuartzFacade.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hawtio-system ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ hawtio-system ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ hawtio-system ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.hawt.jmx.JmxTreeWatcherTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.283 sec - in io.hawt.jmx.JmxTreeWatcherTest
Running io.hawt.web.ProxyDetailsTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.131 sec - in io.hawt.web.ProxyDetailsTest
Running io.hawt.web.RBACRestrictorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in io.hawt.web.RBACRestrictorTest

Results :

Tests run: 18, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ hawtio-system ---
[INFO] Building jar: /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/hawtio-system-1.5-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar-no-fork (attach-sources) @ hawtio-system ---
[INFO] Building jar: /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/hawtio-system-1.5-SNAPSHOT-sources.jar
[INFO] 
[INFO] >>> maven-source-plugin:2.1.2:jar (attach-sources) > generate-sources @ hawtio-system >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-system ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-system ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-system ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-system ---
[INFO] 
[INFO] <<< maven-source-plugin:2.1.2:jar (attach-sources) < generate-sources @ hawtio-system <<<
[INFO] 
[INFO] --- maven-source-plugin:2.1.2:jar (attach-sources) @ hawtio-system ---
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ hawtio-system ---
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/hawtio-system-1.5-SNAPSHOT.jar to /home/oscerd/.m2/repository/io/hawt/hawtio-system/1.5-SNAPSHOT/hawtio-system-1.5-SNAPSHOT.jar
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/pom.xml to /home/oscerd/.m2/repository/io/hawt/hawtio-system/1.5-SNAPSHOT/hawtio-system-1.5-SNAPSHOT.pom
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/hawtio-system-1.5-SNAPSHOT-sources.jar to /home/oscerd/.m2/repository/io/hawt/hawtio-system/1.5-SNAPSHOT/hawtio-system-1.5-SNAPSHOT-sources.jar
[INFO] Installing /home/oscerd/workspace/miscellanea/hawtio/hawtio-system/target/hawtio-system-1.5-SNAPSHOT-sources.jar to /home/oscerd/.m2/repository/io/hawt/hawtio-system/1.5-SNAPSHOT/hawtio-system-1.5-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.127 s
[INFO] Finished at: 2016-07-01T08:16:51+02:00
[INFO] Final Memory: 26M/428M
[INFO] ------------------------------------------------------------------------
```

**Comment by oscerd** [comment]
The only thing I found:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=495505

**Comment by davsclaus** [comment]
I think its reading my git config file, and it fails about invalid git include path.

In my file: `/usr/local/git/etc/gitconfig` I have:
```
[include]	# as of 1.7.10 https://github.com/git/git/commit/9b25a0b52e09400719366f0a33d0d0da98bbf7b0
	path = ~/.gitcinclude
	path = .githubconfig
	path = .gitcredential
```

And I do not have such directory
```
$ ls ~/.gitcinclude
ls: /Users/davsclaus/.gitcinclude: No such file or directory
```

**Comment by davsclaus** [comment]
I am using git version: git version 2.6.4

**Comment by davsclaus** [comment]
Ah yeah seems they have a bug report about this and will get this fixed in a newer release.

So lets wait for that release as this "bug" will cause problems for other hawtio users.

**Comment by oscerd** [comment]
Looking at https://git.eclipse.org/r/#/c/75346/

It seems they still need to merge the fix. So let's wait.

I'll revert on fabric8 and fabric8-forge too.

**Comment by davsclaus** [comment]
Ok closing this

**Comment by oscerd** [comment]
I'm waiting for the next Jgit release :-)

**Comment by rhuss** [comment]
@oscerd @davsclaus what is the working version of jgit ? Because we have the same issue over here https://github.com/fabric8io/fabric8-maven-plugin/issues/231

**Comment by rhuss** [comment]
ah, I see. 0.9.14 is the working one.
