### ISSUE TITLE
Error in ConfigManager.init

### ISSUE THREAD

**Issue by silvestrelosada** [hawtio/hawtio#2219]
I have my spring boot application, it has angular in frontend. And now I'm trying to integrate hawtio-spring-boot to visualize amqp broker. 

I'm using [hawtio-sample-springboot](https://github.com/hawtio/hawtio/tree/master/hawtio-sample-springboot) project as example, When I start the application it is launching the following error 

```
javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662)
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
        at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at io.hawt.system.ConfigManager.init(ConfigManager.java:28)
        at io.hawt.HawtioContextListener.contextInitialized(HawtioContextListener.java:33)
        at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
```

Thanks in advace

**Comment by davsclaus** [comment]
Can you tell more about how you run the application, and what your hawtio and Java version is? 

I cannot reproduce this on master branch with java 7 or 8
