### ISSUE TITLE
Exception when run app

### ISSUE THREAD

**Issue by mystdeim** [hawtio/hawtio#2223]
I downloaded last version (hawtio-app-1.4.66.jar) and get this log when try to start:

> [main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED jolokia-proxy: java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:973)
	at io.hawt.web.ProxyServlet.init(ProxyServlet.java:152)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.run(Main.java:120)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
[main] INFO /hawtio - jolokia-agent: Using policy access restrictor classpath:/jolokia-access.xml
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED o.e.j.w.WebAppContext{/hawtio,file:/home/romanovi/.hawtio/tmp/webapp/},/tmp/hawtio-3589869011714400461.war: java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:973)
	at io.hawt.web.ProxyServlet.init(ProxyServlet.java:152)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.run(Main.java:120)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.handler.HandlerCollection@129b4fe2: java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:973)
	at io.hawt.web.ProxyServlet.init(ProxyServlet.java:152)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.run(Main.java:120)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
[main] WARN org.eclipse.jetty.util.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@5af3a0f: java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:973)
	at io.hawt.web.ProxyServlet.init(ProxyServlet.java:152)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.run(Main.java:120)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:973)
	at io.hawt.web.ProxyServlet.init(ProxyServlet.java:152)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:532)
	at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:344)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.run(Main.java:120)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)

**Comment by tadayosi** [comment]
How did you run hawtio?  In my env, this runs hawtio without any problems.

    $ java -jar hawtio-app-1.4.66.jar

**Comment by mystdeim** [comment]
Yes I use exactly this command. My env oracle-javae 8 and ubuntu 16.04_64

**Comment by tadayosi** [comment]
Have you done any operations on hawtio other than just launching it?  Can you paste the whole log since startup?

**Comment by mystdeim** [comment]
This is full log: https://gist.github.com/mystdeim/8fc0cb6f9699f1ebc334a1062e4278cf Please look

**Comment by tadayosi** [comment]
Doesn't it change even after doing `$ rm -rf ~/.hawtio` ?

**Comment by mystdeim** [comment]
Nope. But I could start hawtio with sudo> seems it work, but I have some warns, please look: [https://gist.github.com/mystdeim/de9f654fc3a86676dbd318b7c219f5e2](https://gist.github.com/mystdeim/de9f654fc3a86676dbd318b7c219f5e2)

Why I should use sudo and how to fix this 'Failed to open browser session, to access hawtio visit "http://localhost:8080/hawtio"'?

**Comment by fabienrousseau** [comment]
We have the same problem/stack trace on a linux server (but works on a linux workstation).

I suspect a classpath issue because after unzipping the standalone jar, then unzipping the hawtio.war file, we discovered that there are 2 jars for "httpcore": httpcore-4.3.2.jar and httpcore-4.4.4.jar.

After verification, the setValidateAfterInactivity exists in 4.4.4 but not in 4.3.2 (links: https://github.com/apache/httpcore/blob/4.4.4/httpcore/src/main/java/org/apache/http/pool/AbstractConnPool.java and https://github.com/apache/httpcore/blob/4.3.2/httpcore/src/main/java/org/apache/http/pool/AbstractConnPool.java )

So probably, sometimes the first jar is loaded, sometimes it's the second.

**Comment by mystdeim** [comment]
Do you plan to fix it?

**Comment by davsclaus** [comment]
@mystdeim how much do you want to pay for a fix .... eh just kidding.

We love contributions, and people is welcome to dive in the code and attempt to fix this. It sound like its that 2 x HTTP JAR on the classpath, so maybe try to track down where this client is used in the various hawt modules, and align their versions to be the same.

**Comment by tadayosi** [comment]
@mystdeim @fabienrousseau Does anyone of you want to contribute? 😄  Otherwise I can fix it.

Anyway, thank you for the bug report and analysis!

**Comment by mystdeim** [comment]
@tadayosi I'm very new in this project, not sure I can do it. I just do bug reporting now )
