### ISSUE TITLE
Terminal plugin does not work on Karaf 4.1.x

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2289]
They changed the api again, and you can find some error in the stacktrace

![screen shot 2017-04-14 at 4 07 25 pm](https://cloud.githubusercontent.com/assets/477100/25045417/91a9ba6a-212c-11e7-9d40-6858c56c1500.png)

**Comment by davsclaus** [comment]
```
2017-04-14 16:08:30,269 | INFO  | qtp761921009-146 | AuthenticationFilter             | 58 - io.hawt.hawtio-karaf-terminal - 1.5.0 | Failed to invoke action null due to:
java.security.PrivilegedActionException
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at javax.security.auth.Subject.doAs(Subject.java:422) [?:?]
	at io.hawt.web.AuthenticationFilter.executeAs(AuthenticationFilter.java:224) [58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at io.hawt.web.AuthenticationFilter.doFilter(AuthenticationFilter.java:162) [58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1691) [92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:72) [111:org.ops4j.pax.web.pax-web-jetty:6.0.3]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [89:org.eclipse.jetty.security:9.3.14.v20161028]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:284) [111:org.ops4j.pax.web.pax-web-jetty:6.0.3]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) [111:org.ops4j.pax.web.pax-web-jetty:6.0.3]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [91:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [83:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [83:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [83:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [94:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [94:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [94:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [94:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [94:org.eclipse.jetty.util:9.3.14.v20161028]
	at java.lang.Thread.run(Thread.java:745) [?:?]
Caused by: java.io.IOException
	at io.hawt.web.plugin.karaf.terminal.TerminalServlet$SessionTerminal.<init>(TerminalServlet.java:163) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at io.hawt.web.plugin.karaf.terminal.TerminalServlet.doPost(TerminalServlet.java:72) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[64:javax.servlet-api:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[64:javax.servlet-api:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712) ~[92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at io.hawt.web.AuthenticationFilter$3.run(AuthenticationFilter.java:227) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	... 30 more
Caused by: java.lang.UnsupportedOperationException
	at org.apache.karaf.shell.impl.console.ConsoleSessionImpl.<init>(ConsoleSessionImpl.java:127) ~[?:?]
	at org.apache.karaf.shell.impl.console.SessionFactoryImpl.create(SessionFactoryImpl.java:139) ~[?:?]
	at io.hawt.web.plugin.karaf.terminal.karaf4.Karaf4ConsoleFactory.createConsole(Karaf4ConsoleFactory.java:44) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at io.hawt.web.plugin.karaf.terminal.TerminalServlet.createSession(TerminalServlet.java:125) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at io.hawt.web.plugin.karaf.terminal.TerminalServlet$SessionTerminal.<init>(TerminalServlet.java:152) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at io.hawt.web.plugin.karaf.terminal.TerminalServlet.doPost(TerminalServlet.java:72) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) ~[64:javax.servlet-api:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[64:javax.servlet-api:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712) ~[92:org.eclipse.jetty.servlet:9.3.14.v20161028]
	at io.hawt.web.AuthenticationFilter$3.run(AuthenticationFilter.java:227) ~[58:io.hawt.hawtio-karaf-terminal:1.5.0]
	... 30 more
```

**Comment by yogeshrao** [comment]
hmmm..this could be because of JLine library upgrade.

**Comment by yogeshrao** [comment]
created a pull request #2295 waiting to merge

**Comment by tadayosi** [comment]
Thanks @yogeshrao for the pull req!
