### ISSUE TITLE
NPE using Tomcat authentication

### ISSUE THREAD

**Issue by andym102** [hawtio/hawtio#2372]
With hawtio deployed as a war in tomcat, attempting to use the tomcat authentication by setting the following properties results in a NullPointerException: 

CATALINA_OPTS=-Dhawtio.authenticationEnabled=true -Dhawtio.role=manager

It looks like this was broken by a recent commit to the TomcatUserDatabaseLoginContext class to support the optional hawtio.tomcatUserFileLocation configuration.  

I worked around the issue by adding the param -Dhawtio.tomcatUserFileLocation=conf

```
WARN  | http-nio-8080-exec-1 | Login failed due java.lang.NullPointerException
        at io.hawt.web.tomcat.TomcatUserDatabaseLoginContext.initialize(TomcatUserDatabaseLoginContext.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:736)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at io.hawt.system.Authenticator.doAuthenticate(Authenticator.java:131)
        at io.hawt.system.Authenticator.authenticate(Authenticator.java:92)  
```

**Comment by andym102** [comment]
version: hawtio-default-offline-1.5.3.war 
env: Apache Tomcat (TomEE)/8.5.6 (7.0.2)
