### ISSUE TITLE
Unknown Host Exception and Login issues

### ISSUE THREAD

**Issue by cnadukula** [hawtio/hawtio#2376]
Hi,

there are two issues, I have:

1. I deployed hawtio-default-offline-1.5.3.war in Apache Artemis, but dropping the war file in Apache Artemis's web folder and  adding it to bootstrap.xml file with the appropriate mapping. this is with no other change. Once artemis starts running i am able to see the hawtio login page, but I am unable to login. I used admin/admin, but still that was of no help. for now I am passing in the arg " -Dhawtio.authenticationEnabled=false" to disable authentication. Is there a way i can set my own users and passwords. I run apache artemis using **Docker** and not the regular way. so it runs in a Docker container. 

2. After i run the docker image for Apache artemis with hawtio in it as mentioned above i see the below error during start up in the logs. Not sure what this error is. Please advise.

java.net.UnknownHostException: ac66b011df9d: ac66b011df9d: System error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at io.hawt.log.support.LogQuerySupport.<init>(LogQuerySupport.java:41)
	at io.hawt.log.log4j.Log4jLogQuery.<init>(Log4jLogQuery.java:37)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.aries.blueprint.utils.ReflectionUtils.newInstance(ReflectionUtils.java:270)
	at org.apache.aries.blueprint.container.BeanRecipe.newInstance(BeanRecipe.java:970)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:325)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:807)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:786)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:341)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.init(BlueprintContainerImpl.java:113)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.<init>(BlueprintContainerImpl.java:73)
	at io.hawt.blueprint.HawtioBlueprintContextListener.contextInitialized(HawtioBlueprintContextListener.java:95)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:876)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:839)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1480)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1442)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:799)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:540)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.apache.activemq.artemis.component.WebServerComponent.start(WebServerComponent.java:134)
	at org.apache.activemq.artemis.cli.commands.Run.execute(Run.java:83)
	at org.apache.activemq.artemis.cli.Artemis.internalExecute(Artemis.java:148)
	at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:95)
	at org.apache.activemq.artemis.cli.Artemis.execute(Artemis.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.activemq.artemis.boot.Artemis.execute(Artemis.java:129)
	at org.apache.activemq.artemis.boot.Artemis.main(Artemis.java:49)
Caused by: java.net.UnknownHostException: ac66b011df9d: System error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 51 more
INFO  | main | Connected to Log4j appender to trap logs with hawtio log plugin
INFO  | main | hawtio using config directory: /root/.hawtio/config
INFO  | main | Clone git repo on startup disabled

**Comment by tadayosi** [comment]
Hi,

Doesn't use of `hawtio-no-slf4j-1.5.3.war` change anything?  In fact JBoss AMQ 7 is composed of the combination of Artemis and hawtio 1.x and it's working just fine. AMQ 7 uses `hawtio-no-slf4j.war`. You can download it for free and compare it with your installation to see if there are any differences:
https://developers.redhat.com/products/amq/download/
