### ISSUE TITLE
V2 - Running hawtio-app.jar causes "ClassNotFoundException: io.hawt.log.log4j.Log4jLogQuery"

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2379]
Running `java -jar hawtio-app-2.0-SNAPSHOT.jar` causes the following error:
```
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to load class io.hawt.log.log4j.Log4jLogQuery from recipe BeanRecipe[name='logFacade']
	at org.apache.aries.blueprint.di.AbstractRecipe.doLoadType(AbstractRecipe.java:195)
	at org.apache.aries.blueprint.di.AbstractRecipe.loadType(AbstractRecipe.java:161)
	at org.apache.aries.blueprint.container.BeanRecipe.loadClass(BeanRecipe.java:242)
	at org.apache.aries.blueprint.container.BeanRecipe.getType(BeanRecipe.java:903)
	at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:317)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate2(BeanRecipe.java:807)
	at org.apache.aries.blueprint.container.BeanRecipe.internalCreate(BeanRecipe.java:786)
	at org.apache.aries.blueprint.di.AbstractRecipe$1.call(AbstractRecipe.java:79)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.aries.blueprint.di.AbstractRecipe.create(AbstractRecipe.java:88)
	at org.apache.aries.blueprint.container.BlueprintRepository.createInstances(BlueprintRepository.java:245)
	at org.apache.aries.blueprint.container.BlueprintRepository.createAll(BlueprintRepository.java:183)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.instantiateEagerComponents(BlueprintContainerImpl.java:383)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.init(BlueprintContainerImpl.java:155)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.init(BlueprintContainerImpl.java:131)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.<init>(BlueprintContainerImpl.java:101)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.<init>(BlueprintContainerImpl.java:90)
	at io.hawt.blueprint.HawtioBlueprintContextListener.contextInitialized(HawtioBlueprintContextListener.java:95)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:782)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:424)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:774)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:249)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1242)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:717)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:494)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:282)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at io.hawt.embedded.Main.run(Main.java:120)
	at io.hawt.embedded.Main.run(Main.java:70)
	at io.hawt.app.App.main(App.java:101)
Caused by: java.lang.ClassNotFoundException: io.hawt.log.log4j.Log4jLogQuery
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:421)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at org.apache.aries.blueprint.container.BlueprintContainerImpl.loadClass(BlueprintContainerImpl.java:171)
	at org.apache.aries.blueprint.container.BlueprintRepository.loadClass(BlueprintRepository.java:410)
	at org.apache.aries.blueprint.container.GenericType.parse(GenericType.java:90)
	at org.apache.aries.blueprint.di.AbstractRecipe.doLoadType(AbstractRecipe.java:168)
	... 33 more
```

**Comment by tadayosi** [comment]
`Log4jLogQuery` came from hawtio-insight-log, which was deprecated and removed. We just need to remove the reference.
