### ISSUE TITLE
Username / password with hawt-app queries for non-existant mbean

### ISSUE THREAD

**Issue by wsargent** [hawtio/hawtio#2382]
I have a Jolokia server set up using a [custom JAAS module to Yubikey](https://github.com/Yubico/yubico-java-client/tree/master/jaas):

```
java -javaagent:lib/jolokia-jvm-1.3.7-agent.jar=port=8778,protocol=https,debug=true,host=localhost,authMode=jaas,useSslClientAuthentication=false,keystorePassword=changeit,realm=YubikeyAuth,keystore=$CERTSDIR/jolokia.jks \
-Djava.security.auth.login.config=$CONFDIR/yubikey.config com.example.JolokiaServer
```

Where Main is:

```scala
package com.example

import java.lang.management.ManagementFactory
import java.util
import java.util.concurrent.ArrayBlockingQueue
import javax.management.ObjectName

object JolokiaServer {
  def main(args: Array[String]): Unit = {
    val mbs = ManagementFactory.getPlatformMBeanServer

    // Construct the ObjectName for the Hello MBean we will register
    val mbeanName: ObjectName = new ObjectName("com.example:type=Hello")

    // Create the Hello World MBean
    val mbean: Hello = new Hello

    // Register the Hello World MBean
    mbs.registerMBean(mbean, mbeanName)

    // Construct the ObjectName for the QueueSampler MXBean we will register
    val mxbeanName: ObjectName = new ObjectName("com.example:type=QueueSampler")

    // Create the Queue Sampler MXBean
    val queue: util.Queue[String] = new ArrayBlockingQueue[String](10)
    queue.add("Request-1")
    queue.add("Request-2")
    queue.add("Request-3")
    val mxbean: QueueSampler = new QueueSampler(queue)

    // Register the Queue Sampler MXBean
    mbs.registerMBean(mxbean, mxbeanName)

    Future {
      blocking {
        if (StdIn.readLine("Press RETURN to stop...\n") != null)
          System.exit(1)
      }
    }
  }
}
```

And I'm trying to connect to it using the standalone hawtio app, using the following command line:

```
java \
  -Djavax.net.ssl.keyStore=$CONFDIR/certs/client.jks \
  -Djavax.net.ssl.keyStorePassword=changeit \
  -Djavax.net.ssl.keyStoreType=jks \
  -Djavax.net.ssl.trustStore=$CONFDIR/certs/cacerts-plus-clientca.jks \
  -Djavax.net.ssl.trustStoreType=jks \
  -Djavax.net.ssl.trustStorePassword=changeit \
  -Dhawtio.authenticationEnabled=true \
  -Dhawtio.offline=true \
  -jar $HOME/.ivy2/cache/io.hawt/hawtio-app/jars/hawtio-app-2.0.0.jar
```

The hawt io starts up with connection settings without the username and password when first loading -- if I refresh the page then I do see "User name:" and "Password" fields.  I type in my username and hold down the Yubikey so I can get the OTP... and it fails saying that the client is querying for an mbean 'hawtio:type=security,name=RBACRegistry' on the Jolokia server (which is running as an agent, not in a WAR or anything). 

Here are the server logs:

```
[info] DEBUG c.y.j.YubikeyLoginModule - Initializing YubikeyLoginModule
[info] DEBUG c.y.j.YubikeyLoginModule - Trying to instantiate com.yubico.jaas.impl.YubikeyToUserMapImpl
[info] DEBUG c.y.j.YubikeyLoginModule - Begin OTP login
[info] TRACE c.y.j.YubikeyLoginModule - Checking OTP vvktrbkgjekgrtvifnelnhkgihflghclhddfdtetngin
[info] TRACE c.y.j.YubikeyLoginModule - OTP vvktrbkgjekgrtvifnelnhkgihflghclhddfdtetngin verify result : OK
[info] INFO c.y.j.YubikeyLoginModule - OTP verified successfully (YubiKey id vvktrbkgjekg)
[info] DEBUG c.y.j.YubikeyLoginModule - Check if YubiKey vvktrbkgjekg belongs to user wsargent
[info] TRACE c.y.j.YubikeyLoginModule - In commit()
[info] DEBUG c.y.j.YubikeyLoginModule - Committing principal <YubikeyPrincipal>vvktrbkgjekg
[info] D> URI: /jolokia/list/hawtio/type=security,name=RBACRegistry?maxDepth=7&maxCollectionSize=50000&ignoreErrors=true&canonicalNaming=false
[info] D> Path-Info: list/hawtio/type=security,name=RBACRegistry
[info] D> Request: JmxListRequest[, path=[hawtio, type=security,name=RBACRegistry]]
[info] E> Error 400
[error] java.lang.IllegalArgumentException: No MBean 'hawtio:type=security,name=RBACRegistry' found
[error] 	at org.jolokia.handler.ListHandler.doHandleRequest(ListHandler.java:102)
[error] 	at org.jolokia.handler.ListHandler.doHandleRequest(ListHandler.java:42)
[error] 	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:161)
[error] 	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:156)
[error] 	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:99)
[error] 	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:413)
[error] 	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)
[error] 	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
[error] 	at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
[error] 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.executeGetRequest(JolokiaHttpHandler.java:265)
[error] 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:230)
[error] 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler$1.run(JolokiaHttpHandler.java:190)
[error] 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler$1.run(JolokiaHttpHandler.java:188)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at javax.security.auth.Subject.doAs(Subject.java:422)
[error] 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandleAs(JolokiaHttpHandler.java:188)
[error] 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:176)
[error] 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
[error] 	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:72)
[error] 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
[error] 	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
[error] 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
[error] 	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: javax.management.InstanceNotFoundException: InstanceNotFoundException for MBean hawtio:type=security,name=RBACRegistry (hawtio:type=security,name=RBACRegistry)
[error] 	at org.jolokia.handler.list.MBeanInfoData.handleException(MBeanInfoData.java:243)
[error] 	at org.jolokia.handler.ListHandler$ListMBeanEachAction.lookupMBeanInfo(ListHandler.java:212)
[error] 	at org.jolokia.handler.ListHandler$ListMBeanEachAction.execute(ListHandler.java:200)
[error] 	at org.jolokia.handler.ListHandler$ListMBeanEachAction.execute(ListHandler.java:154)
[error] 	at org.jolokia.backend.executor.AbstractMBeanServerExecutor.call(AbstractMBeanServerExecutor.java:90)
[error] 	at org.jolokia.handler.ListHandler.doHandleRequest(ListHandler.java:95)
[error] 	... 25 more
[info] DEBUG c.y.j.YubikeyLoginModule - Initializing YubikeyLoginModule
[info] DEBUG c.y.j.YubikeyLoginModule - Trying to instantiate com.yubico.jaas.impl.YubikeyToUserMapImpl
[info] DEBUG c.y.j.YubikeyLoginModule - Begin OTP login
[info] TRACE c.y.j.YubikeyLoginModule - Checking OTP vvktrbkgjekgrtvifnelnhkgihflghclhddfdtetngin
[info] TRACE c.y.j.YubikeyLoginModule - OTP vvktrbkgjekgrtvifnelnhkgihflghclhddfdtetngin verify result : REPLAYED_OTP
[info] DEBUG c.y.j.YubikeyLoginModule - OTP validation returned REPLAYED_OTP
[info] INFO c.y.j.YubikeyLoginModule - None out of 1 possible YubiKey OTPs for user wsargent validated successful
```

Any idea what it's doing and how to work with that?  I don't see anything in the documentation about this, and I'm not running Java EE on the server side.

**Comment by wsargent** [comment]
Even stranger -- I can see that there's `io.hawt.jmx.RBACRegistry` in hawtio-system in Github, but when I look at the artifacts on https://mvnrepository.com/artifact/io.hawt/hawtio-system the class isn't there in the JAR!

**Comment by wsargent** [comment]
Running with hawt.io 1.5.4 I can get further

```
java \
  -Djavax.net.ssl.keyStore=$CONFDIR/certs/client.jks \
  -Djavax.net.ssl.keyStorePassword=changeit \
  -Djavax.net.ssl.keyStoreType=jks \
  -Djavax.net.ssl.trustStore=$CONFDIR/certs/cacerts-plus-clientca.jks \
  -Djavax.net.ssl.trustStoreType=jks \
  -Djavax.net.ssl.trustStorePassword=changeit \
  -Dhawtio.offline=true \
  -jar lib/hawtio-app-1.5.4.jar
```

I still get the not found response but an HTTP authentication dialog pops up which I have to enter the OTP password on every time. 

```
[info] DEBUG c.y.j.YubikeyLoginModule - Initializing YubikeyLoginModule
[info] DEBUG c.y.j.YubikeyLoginModule - Trying to instantiate com.yubico.jaas.impl.YubikeyToUserMapImpl
[info] DEBUG c.y.j.YubikeyLoginModule - Begin OTP login
[info] TRACE c.y.j.YubikeyLoginModule - Checking OTP vvktrbkgjekggeikbcucejcdgdtueunhhvivegkuditb
[info] TRACE c.y.j.YubikeyLoginModule - OTP vvktrbkgjekggeikbcucejcdgdtueunhhvivegkuditb verify result : OK
[info] INFO c.y.j.YubikeyLoginModule - OTP verified successfully (YubiKey id vvktrbkgjekg)
[info] DEBUG c.y.j.YubikeyLoginModule - Check if YubiKey vvktrbkgjekg belongs to user wsargent
[info] TRACE c.y.j.YubikeyLoginModule - In commit()
[info] DEBUG c.y.j.YubikeyLoginModule - Committing principal <YubikeyPrincipal>vvktrbkgjekg
[info] E> Error 400
[error] java.lang.IllegalArgumentException: No MBean 'hawtio:type=security,name=RBACRegistry' found
[error] 	at org.jolokia.handler.ListHandler.doHandleRequest(ListHandler.java:102)
[error] 	at org.jolokia.handler.ListHandler.doHandleRequest(ListHandler.java:42)
[error] 	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:161)
[error] 	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:156)
[error] 	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:99)
[error] 	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:413)
[error] 	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)
[error] 	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
[error] 	at org.jolokia.http.HttpRequestHandler.handleGetRequest(HttpRequestHandler.java:86)
```

In addition, I get a http://localhost:8080/hawtio/login page with 1.5.4, but typing a username and password seems to do nothing:

```
[qtp1030870354-23] INFO io.hawt.web.keycloak.KeycloakServlet - Keycloak integration is disabled
[qtp1030870354-24] INFO io.hawt.web.LoginServlet - hawtio login is using 1800 sec. HttpSession timeout
[qtp1030870354-24] WARN io.hawt.web.LoginServlet - No security subject stored in existing session, invalidating
```

So I think the main thing is to how to best deal with this guy given a standalone app:

```
[main] INFO io.hawt.web.RBACMBeanInvoker - Using MBean [hawtio:type=security,area=jmx,rank=0,name=HawtioDummyJMXSecurity] for role based access control
```

**Comment by skarsaune** [comment]
A couple of quick questions, without knowing all the details here: 

1. What happens if you enter a url manually, e.g. /hawtio/threads , do you still get directed back to login?
2. Is there any difference if you tick "remember me", on the login page?
