### ISSUE TITLE
Spring Boot RBACRegistry double registration

### ISSUE THREAD

**Issue by ThorstenKunz** [hawtio/hawtio#2406]
Reproduce: create a simple spring boot application and configure two different ports like this in application.properties

```
server.port=10000
management.port=10001
```
This will result in a 
```
Caused by: javax.management.InstanceAlreadyExistsException: hawtio:type=security,name=RBACRegistry
	at com.sun.jmx.mbeanserver.Repository.addMBean(Unknown Source) ~[na:1.8.0_141]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(Unknown Source) ~[na:1.8.0_141]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(Unknown Source) ~[na:1.8.0_141]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(Unknown Source) ~[na:1.8.0_141]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source) ~[na:1.8.0_141]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source) ~[na:1.8.0_141]
	at io.hawt.jmx.RBACRegistry.init(RBACRegistry.java:64) ~[hawtio-system-1.5.5.jar:1.5.5]
	at io.hawt.HawtioContextListener.contextInitialized(HawtioContextListener.java:43) ~[hawtio-system-1.5.5.jar:1.5.5]
	... 24 common frames omitted
```
 exception

**Comment by tadayosi** [comment]
What version of hawtio are you using?  The exception is thrown typically when more than one hawtio instances are being deployed on a single JVM. Are you using `@EnableHawtio`?  If so please drop it. This annotation is no longer needed for the latest version of hawtio.

**Comment by ThorstenKunz** [comment]
Thanks, I didn't know that `@EnableHawtio`wasn't needed anymore. I dropped it an the error was gone.

Thanks
