### ISSUE TITLE
hawtio CI website build is failing

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2413]
Probably due to some stale JavaScript package.
https://circleci.com/gh/hawtio/hawtio/1430

**Comment by jamesnetherton** [comment]
Would be better if we ran Maven in batch mode, then we wouldn't have so much noise in the build logs.

**Comment by tadayosi** [comment]
This is probably the root cause: https://github.com/shinnn/gulp-gh-pages/issues/116
```
[01:54:48] deploy 1502 items

/home/ubuntu/hawtio/website/node_modules/gulp-gh-pages/node_modules/gift/lib/commit.js:145
      ref1 = /^.+? (.*) (\d+) .*$/.exec(line), m = ref1[0], actor = ref1[1], e
                                                       ^
TypeError: Cannot read property '0' of null
    at Function.module.exports.Commit.actor (/home/ubuntu/hawtio/website/node_modules/gulp-gh-pages/node_modules/gift/lib/commit.js:145:56)
    at Function.module.exports.Commit.parse_commits (/home/ubuntu/hawtio/website/node_modules/gulp-gh-pages/node_modules/gift/lib/commit.js:111:21)
    at /home/ubuntu/hawtio/website/node_modules/gulp-gh-pages/node_modules/gift/lib/commit.js:55:39
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

./ci-website.sh returned exit code 8

Action failed: ./ci-website.sh
```

**Comment by jamesnetherton** [comment]
We could maybe use this fork until the fix is merged?

https://www.npmjs.com/package/gulp-gh-pages-gift

**Comment by tadayosi** [comment]
@jamesnetherton oops, yeah that looks better. Let me change again.
