### ISSUE TITLE
V2 - latest hawtio.war doesn't get deployed on Apache Karaf 4.1.3

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2440]
It looks like there's a bug in pax-web-extender 6.0.7 with `<session-config>` in `web.xml`:
```
2018-02-27 13:41:45,662 | ERROR | FelixStartLevel  | WebObserver                      | 161 - org.ops4j.pax.web.pax-web-extender-war - 6.0.7 | Error scanning web bundle io.hawt.hawtio-war [169]: null
java.lang.NullPointerException: null
	at org.ops4j.pax.web.extender.war.internal.parser.WebAppParser.parseSessionConfig(WebAppParser.java:489) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.parser.WebAppParser.parseApp(WebAppParser.java:165) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.parser.WebAppParser.parse(WebAppParser.java:104) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.WebObserver.createExtension(WebObserver.java:145) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.Activator.doCreateExtension(Activator.java:82) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.extender.AbstractExtender.createExtension(AbstractExtender.java:259) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:242) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.ops4j.pax.web.extender.war.internal.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:54) [161:org.ops4j.pax.web.pax-web-extender-war:6.0.7]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482) [?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415) [?:?]
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) [?:?]
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444) [?:?]
	at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915) [?:?]
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834) [?:?]
	at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516) [?:?]
	at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4578) [?:?]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2173) [?:?]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1372) [?:?]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```

**Comment by tadayosi** [comment]
I'll test it with Karaf 4.1.5 and see if it's resolved.

**Comment by tadayosi** [comment]
@akieling Yes, it's related but your changes are totally fine. As far as I checked the pax-web-extender code it's a bug in pax-web-extender, and it looks like the bug is fixed in its latest branch. It's just a matter of which versions of Karaf the fix is available on.

**Comment by tadayosi** [comment]
@akieling Btw, what's the reason behind adding `<session-config>` in `web.xml`?  Is there any ticket that explained it?

**Comment by akieling** [comment]
@tadayosi  It's just a good security practice but I made the change without a ticket explaining the issue, which wasn't great.
https://www.owasp.org/index.php/HttpOnly

**Comment by tadayosi** [comment]
I confirmed the pax-web-extender fix is not yet available on Karaf 4.1.5. Maybe we need to wait for Karaf 4.2 to get it fixed.

**Comment by tadayosi** [comment]
It's a bit too drastic to drop support for Karaf 4.1.x in hawtio v2.
