### ISSUE TITLE
ServiceMix7 install error

### ISSUE THREAD

**Issue by sekaijin** [hawtio/hawtio#2446]
Hi
install on servicemix 7.0.1 Java 1.8.0_102 karaf 4.0.9
feature:repo-add hawtio 1.5.7
feature:install hawtio

`2018-03-15 18:54:58,109 | ERROR | Thread-16        | ShellUtil                        | 124 - org.apache.karaf.shell.core - 4.0.9 | Exception caught while executing command
org.osgi.framework.BundleException: Could not create bundle object.
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3078)[org.apache.felix.framework-5.6.2.jar:]
        at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)[org.apache.felix.framework-5.6.2.jar:]
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundle0(BundleIdBasedRegion.java:117)[8:org.apache.karaf.features.core:4.0.9]
        at org.eclipse.equinox.internal.region.BundleIdBasedRegion.installBundleAtLocation(BundleIdBasedRegion.java:97)[8:org.apache.karaf.features.core:4.0.9]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installBundle(FeaturesServiceImpl.java:1261)[8:org.apache.karaf.features.core:4.0.9]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:739)[8:org.apache.karaf.features.core:4.0.9]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1176)[8:org.apache.karaf.features.core:4.0.9]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:1074)[8:org.apache.karaf.features.core:4.0.9]
        at java.util.concurrent.FutureTask.run(Unknown Source)[:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)[:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)[:1.8.0_102]
        at java.lang.Thread.run(Unknown Source)[:1.8.0_102]
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
        at java.util.zip.ZipFile.read(Native Method)[:1.8.0_102]
        at java.util.zip.ZipFile.access$1400(Unknown Source)[:1.8.0_102]
        at java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)[:1.8.0_102]
        at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)[:1.8.0_102]
        at java.util.zip.InflaterInputStream.read(Unknown Source)[:1.8.0_102]
        at java.io.FilterInputStream.read(Unknown Source)[:1.8.0_102]
        at org.apache.felix.framework.util.WeakZipFileFactory$WeakZipFile$WeakZipInputStream.read(WeakZipFileFactory.java:709)[org.apache.felix.framework-5.6.2.jar:]
        at org.apache.felix.framework.cache.JarRevision.getMainAttributes(JarRevision.java:229)[org.apache.felix.framework-5.6.2.jar:]
        at org.apache.felix.framework.cache.JarRevision.getManifestHeader(JarRevision.java:104)[org.apache.felix.framework-5.6.2.jar:]
        at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1274)[org.apache.felix.framework-5.6.2.jar:]
        at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:113)[org.apache.felix.framework-5.6.2.jar:]
        at org.apache.felix.framework.Felix.installBundle(Felix.java:3025)[org.apache.felix.framework-5.6.2.jar:]
        ... 11 more`

Thank

**Comment by jamesnetherton** [comment]
Bit of a late response but it seems you maybe had a corrupted JAR somewhere (hence the 'invalid LOC header' message). The install worked fine for me:

```
2018-11-13 15:28:50,535 | INFO  | ender-2-thread-2 | JmxTreeWatcher                   | 231 - io.hawt.hawtio-web - 1.5.7 | Welcome to hawtio 1.5.7 : http://hawt.io/ : Don't cha wish your console was hawt like me? ;-)
```

**Comment by sekaijin** [comment]
Thank
I will try again by emptying the cache of maven and nexus
