### ISSUE TITLE
Hawtio 1.5.8 does not work with Spring Boot 2.0

### ISSUE THREAD

**Issue by mikem4600** [hawtio/hawtio#2453]
Spring Boot 2.0  no longer includes the class org.springframework.boot.actuate.endpoint.mvc.AbstractNamedMvcEndpoint.

As such, when using hawtio-springboot, application startup fails with the following exception:

2018-03-21 14:31:54,749 [main] [ERROR] o.s.boot.SpringApplication - Application run failed 
java.lang.IllegalStateException: Error processing condition on io.hawt.springboot.HawtioAutoConfiguration.hawtioEndpoint
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:109)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:179)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:328)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
	at com.intracom.microservice.example.util.Launcher.main(Launcher.java:18)
Caused by: java.lang.IllegalStateException: @ConditionalOnMissingBean did not specify a bean using type, name or annotation and the attempt to deduce the bean's type failed
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.validate(OnBeanCondition.java:390)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:380)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:114)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
	... 17 common frames omitted
Caused by: org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanTypeDeductionException: Failed to deduce bean type for io.hawt.springboot.HawtioAutoConfiguration.hawtioEndpoint
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanTypeForBeanMethod(OnBeanCondition.java:443)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanType(OnBeanCondition.java:427)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:374)
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/mvc/AbstractNamedMvcEndpoint
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:264)
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanTypeForBeanMethod(OnBeanCondition.java:437)
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.mvc.AbstractNamedMvcEndpoint
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 common frames omitted

**Comment by tadayosi** [comment]
Spring Boot 2.0 is not yet supported. It's however a nice idea to support it.

**Comment by davsclaus** [comment]
The actuator api is totally changed in SB2, so we may need to have a hawtio-spring-boot2 module for SB2 only.

**Comment by micke-a** [comment]
I would love for SB2 to be supported by hawtio!

Currently in a Catch 22 sort of situation where 
- I want/need (file idempotent repo cache size bug) to migrate to the  latest Camel version (2.22.0)
- For this I need to migrate to SB2
- Cannot migrate to SB2 without loosing Hawtio which depends on SB1

**Comment by mageddo** [comment]
As a workaround to use the JMX actions (no authentication) I did the follow:

Grade 

```groovy
dependencies {
		compile group: 'io.hawt', name: 'hawtio-system', version: '2.0.2'
		compileOnly group: 'io.hawt', name: 'hawtio-default', version: '2.0.2'
}
processResources {
	doLast {
		def dep = project.configurations.compileOnly.filter { it.name.contains('hawtio-default') }.singleFile
		ant.unzip(src: dep, dest: new File(project.sourceSets.main.output.resourcesDir, "hawtio-static")){
			patternset(excludes: '**/WEB-INF/**,**/META-INF/**')
		}
	}
}
```

```java
import io.hawt.web.proxy.ProxyServlet;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.InputStreamResource;
import org.springframework.core.io.Resource;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;

@Controller
@RequestMapping("/hawtio")
public class HawtioConfig implements WebMvcConfigurer {

	@Value("${:classpath:/hawtio-static/index.html}")
	private Resource index;

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry
			.addResourceHandler("/hawtio/**")
			.addResourceLocations("classpath:/hawtio-static/");
	}

	@Bean
	public ServletRegistrationBean servletRegistrationBean(){
		return new ServletRegistrationBean(new ProxyServlet(),"/hawtio/proxy/*");
	}

	@GetMapping(value = {"", "/"}, produces = MediaType.TEXT_HTML_VALUE)
	public String redirect(final HttpServletRequest request) {
		return getIndexHtmlRedirect(request);
	}

	@GetMapping(value = {"/jmx/*", "/jvm/*"}, produces = MediaType.TEXT_HTML_VALUE)
	@ResponseBody
	public ResponseEntity actions() throws IOException {
		return ResponseEntity.ok(new InputStreamResource(index.getInputStream()));
	}

	protected String getIndexHtmlRedirect(final HttpServletRequest request) {
		final ServletUriComponentsBuilder builder = ServletUriComponentsBuilder
			.fromRequest(request);
		return "redirect:" + builder.path("/index.html").build().toString();
	}
}

```

**Comment by micheljung** [comment]
With Spring Boot 2 being GA for over 6 months now (and almost nobody creating Spring Boot 1.x projects anymore), I think this should become a top priority.

**Comment by pacoja84** [comment]
> 2\. va -Dhawtio.proxyWhitelist='*' -jar hawtio-app-2.0.3.jar --port 8090

Just to add that you are using Spring boot for non web application(Camel in our case), you should also add the "web starter"

	<dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-starter-web</artifactId>
	</dependency>

**Comment by oliverkuntze** [comment]
> Hi Folks,
> Here's a workaround that helped us:
> 
> 1. Created a Springboot 2.0.4 app with these two dependencies:
>    `spring-boot-starter-actuator`
>    `jolokia-core`
>    and the application.yml has these settings:
>    `management: endpoints: web: exposure: include: '*'`
> 2. Used the hawt.io standalone app like this
>    `java -Dhawtio.proxyWhitelist='*' -jar hawtio-app-2.0.3.jar --port 8090`
> 3. Was able then to connect to our AWS hosted Springboot app and we can see our CAMEL routes without problems.
> 
> Cheers!

Have you secured your jolokia actuator endpoint? 
I did secure mine but hawtio somehow circumvents the basic auth in my app. No credentials needed to for hawtio to access the endpoint.
Did you experience the same?

**Comment by checomar** [comment]
https://github.com/hawtio/hawtio/issues/2453#issuecomment-431389516
Oliver, I experienced the same and sorry, I haven't found a way to secure them. For now we are resorting to keep those camel springboot apps behind a managed VPN

**Comment by Namphibian** [comment]
I ran into this yesterday and today it is fixed. Awesome work guys!

**Comment by DarkStar1** [comment]
I'm trying this out with Jolokia-core 1.6.0 and springboot release 2.0.6 and it does not work unfortunately. MightI ask, @Namphibian , what setup did you use?

**Comment by checomar** [comment]
@DarkStar1  for what is worth.
Got ours working with Java 8, SB 2.0.4 and let mvn manage the jolokia version.  We are sticking with Java8 for now since some legacy libraries have issues with newest versions.
