### ISSUE TITLE
Slow reverse DNS in io.hawt.system.ProxyWhitelist blocks Spring Boot startup

### ISSUE THREAD

**Issue by adrian-baker** [hawtio/hawtio#2466]
Using hawtio-springboot, I was confused as to why my tiny application was taking 40 seconds to start up.

Thread dumps revealed it was stuck in io.hawt.system.ProxyWhitelist.initialiseWhitelist() . I tried to workaround by adding an explicit whitelist with `hawtio.proxyWhitelist`, however it appears to still then try automatically adding localhost names to this list. Nor can I see any way to disable the remote connection plugin (we don't use it).

    "restartedMain" #13 prio=5 os_prio=0 tid=0x000000002d426000 nid=0x2614 runnable [0x000000002e0ee000]
    java.lang.Thread.State: RUNNABLE
            at java.net.Inet6AddressImpl.getHostByAddr(Native Method)
            at java.net.InetAddress$2.getHostByAddr(InetAddress.java:932)
            at java.net.InetAddress.getHostFromNameService(InetAddress.java:617)
            at java.net.InetAddress.getCanonicalHostName(InetAddress.java:588)
            at io.hawt.system.ProxyWhitelist.initialiseWhitelist(ProxyWhitelist.java:86)
            at io.hawt.system.ProxyWhitelist.<init>(ProxyWhitelist.java:45)
            at io.hawt.web.ProxyServlet.init(ProxyServlet.java:116)
            at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
            at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421)
            at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
            at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
            at org.springframework.boot.context.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
            at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.handleDeferredInitialize(JettyEmbeddedServletContainer.java:205)
            at org.springframework.boot.context.embedded.jetty.JettyEmbeddedServletContainer.start(JettyEmbeddedServletContainer.java:138)
            - locked <0x0000000722076718> (a java.lang.Object)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
            - locked <0x000000071fbf2a90> (a java.lang.Object)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
            at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(EndpointWebMvcAutoConfiguration.java:193)
            at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.afterSingletonsInstantiated(EndpointWebMvcAutoConfiguration.java:156)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
            at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
            - locked <0x00000005c0d46260> (a java.lang.Object)
            at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
            at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
            at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
            at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
            at nz.co.tvnz.MainApplication.main(MainApplication.java:13)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

**Comment by tadayosi** [comment]
Aren't you using Mac?  If so, there's a known issue with Mac and `java.net.InetAddress`:
https://thoeni.io/post/macos-sierra-java/
which is not specific to Hawtio.

**Comment by adrian-baker** [comment]
Windows.

Although slowness isn't caused by hawtio itself, reverse DNS is often problematic or slow, as the OSX issue above indicates. I'd suggest doing these lookups asynchronously, on demand (when the remote connect feature is used, for example), or offering a way to disable them.

Others avoid the issue by using alternatives to java.net, like  http://www.dnsjava.org/ .

**Comment by tadayosi** [comment]
OK, so my understanding is, it's not a OS issue but can be caused depending on the performance of network server in your environment, right?  Most Windows users won't face this issue but some with slow reverse DNS like your env still see it?

I think the problem is then Hawtio always tries to probe hostnames of the localhost. What about providing users with an option to disable the probing who want to configure the whitelist by themselves?

**Comment by adrian-baker** [comment]
I'd assumed this was a combination of Java + Windows, for example https://stackoverflow.com/questions/28198365/rerverse-dns-lookups-on-windows-block-for-several-seconds-for-unresolvable-ip-ad  , https://www.mirthcorp.com/community/issues/browse/MIRTH-3070 .

> What providing users with an option to disable the probing who want to configure the whitelist by themselves?

That works for the users that have gone to the effort of taking thread dumps during slow start to work out they need to disable the whitelist. Most people aren't going to go that far though. 

Would it not be better to lazily build the proxy client in `io.hawt.web.ProxyServlet`, when `service(..)` is first called? It seems wasteful to do all of the work in init synchronously, blocking startup, for resources that are normally never used.

**Comment by tadayosi** [comment]
`ProxyServlet` is actually the backend for Connect plugin, and while it's not useful for Spring Boot it's indeed used in other use cases such as hawtio-app.jar and hawtio.war where users want to monitor/manager multiple JVM instances from a single point.

**Comment by tadayosi** [comment]
Doesn't `loadOnStartup` to `-1` lazily init the servlet?  Why isn't it enough?

**Comment by adrian-baker** [comment]
That would work. I think that would require a code change though.

**Comment by tadayosi** [comment]
Looks like CXF had the same issue (and fix): https://issues.apache.org/jira/browse/CXF-7671
