### ISSUE TITLE
hawt.io/jolokia gives user blank screen if JMX call throws an NPE

### ISSUE THREAD

**Issue by exabrial** [hawtio/hawtio#2515]
Hawtio doesn't work out of the box.

1. Drop an unsecured jolokia agent on a remote machine
1. Down the hawtio 2.10 jar. 
1. Run it from the command line
1. Try to connect to remote jolokia agent. You'll be prompted for a password (even through there is none)

**Comment by tadayosi** [comment]
Have you configured `hawtio.proxyWhitelist`?  Also, have you checked the CORS settings for the remote jolokia agent?

**Comment by exabrial** [comment]
Thanks for the reply! So we configured the whitelist, but now we're getting a white screen. Does the proxy do CORS preflights? I wouldn't think that configuring it would be necessary.

**Comment by exabrial** [comment]
Also it looks like it got data back from the agent, so it's likely not cors

**Comment by exabrial** [comment]
This took _a lot_ of problem solving but we figured it out! This patch here breaks hawtio: https://github.com/apache/tomee/pull/166

**Comment by exabrial** [comment]
Take a look at that PR, I put some notes on how to reproduce the issue. I can send you the config file that breaks hawtio if I can email you

**Comment by exabrial** [comment]
Actually, I think I know what it is. Trying creating an MBean that throws an `NullPointerException` when it tries to list the attributes/operations

**Comment by tadayosi** [comment]
Great investigation. So can/should TomEE handle the NPE?  Or should Hawtio be robust enough to handle it?

**Comment by exabrial** [comment]
Definitely a bug in both pieces of software that needs to be fixed. I'm not sure on the jmx side of if the problem is jolokia or hawtio though

**Comment by exabrial** [comment]
was able to get you a stack trace by putting a exception breakpoint into the JVM:

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:98)
	at org.jolokia.handler.ExecHandler.doHandleRequest(ExecHandler.java:40)
	at org.jolokia.handler.JsonRequestHandler.handleRequest(JsonRequestHandler.java:89)
	at org.jolokia.backend.MBeanServerExecutorLocal.handleRequest(MBeanServerExecutorLocal.java:109)
	at org.jolokia.backend.MBeanServerHandler.dispatchRequest(MBeanServerHandler.java:161)
	at org.jolokia.backend.LocalRequestDispatcher.dispatchRequest(LocalRequestDispatcher.java:99)
	at org.jolokia.backend.BackendManager.callRequestDispatcher(BackendManager.java:428)
	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:158)
	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
	at org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:137)
	at org.jolokia.http.AgentServlet$3.handleRequest(AgentServlet.java:460)
	at org.jolokia.http.AgentServlet.handleSecurely(AgentServlet.java:350)
	at org.jolokia.http.AgentServlet.handle(AgentServlet.java:321)
	at org.jolokia.http.AgentServlet.doPost(AgentServlet.java:284)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.auth.LoginRedirectFilter.doFilter(LoginRedirectFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at io.hawt.web.auth.SessionExpiryFilter.process(SessionExpiryFilter.java:105)
	at io.hawt.web.auth.SessionExpiryFilter.doFilter(SessionExpiryFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.hawt.jmx.RBACRegistry.jsonifyMBeanInfo(RBACRegistry.java:181)
	at io.hawt.jmx.RBACRegistry.list(RBACRegistry.java:133)
	... 90 more
```

**Comment by exabrial** [comment]
It looks like  `mBeanInfo.getAttributes()` returning null isn't accounted for. *Why* it's returning null is a separate issue, but it would be best to give the user a warning like "hey, we got an exception" rather than just show a white screen

**Comment by tadayosi** [comment]
@exabrial Thanks!  I've quickly created a fix at this branch: https://github.com/hawtio/hawtio/tree/issue-2515
Can you check it out and run `mvn clean install` locally, then test the created hawtio-app.jar to see if the issue is resolved?

**Comment by exabrial** [comment]
Works! And the TomEE people have solved the bug on their end as well

**Comment by tadayosi** [comment]
OK, let's merge the fix to master.
