### ISSUE TITLE
hawtio:2.2.0 Missing Local Tab under Connect and Keycloak Error

### ISSUE THREAD

**Issue by vivek42** [hawtio/hawtio#2540]
We are trying to update our hawtio version from 1.4.48 to 2.2.0. However, newer version does not seem to have a local tab under Connect. We have tried making a local connection under Remote tab option, but nothing happens. Also, under Logs tab on the home page we see this error -

ERROR | io.hawt.web.filters.ContentSecurityPolicyFilter | Can't read keycloak configuration file

However, since our previous deployment didn't use keycloak for security we are planning not to use keycloak integration. How do I get rid of this error? 

Kindly help. We are using apache tomee - 1.7.5.

**Comment by tadayosi** [comment]
Yes, Local tab no longer exists in Hawtio v2. The Keycloak error is weird, you don't need to use it at all so the servlet filter shouldn't show such an ERROR log. Have you configured `hawtio.keycloakConfigClient` system property or servlet config parameter somewhere in your application?  Otherwise you shouldn't get the error.

Also, to investigate the issue further please paste the entire stacktrace following the error message.

**Comment by vivek42** [comment]
Below is the stack trace from the catalina.out file -

```
ERROR | localhost-startStop-1 | Can't read keycloak configuration file
java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at io.hawt.web.filters.ContentSecurityPolicyFilter.init(ContentSecurityPolicyFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4908)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5602)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```
We used JAAS for hawtio authentication. I tried setting hawtio.keycloakEnabled=false, however, it didn't help.

**Comment by tadayosi** [comment]
Thanks. It's weird indeed as the stacktrace shows `hawtio.keycloakConfigClient` is somehow set to `""` instead of `null`.

@grgrzybek Do you see any possibility in this code that `keycloakConfigFile` is set to `""`?  I can't see other than `hawtio.keycloakConfigClient` is set externally elsewhere.
https://github.com/hawtio/hawtio/blob/hawtio-2.2.0/hawtio-system/src/main/java/io/hawt/web/filters/ContentSecurityPolicyFilter.java#L38-L58

**Comment by grgrzybek** [comment]
That's strange. Looks like either config or system property is set, but to some wrong value:
```
        String keycloakConfigFile = getConfigParameter(KeycloakServlet.KEYCLOAK_CLIENT_CONFIG);
        if (keycloakConfigFile == null && System.getProperty(KeycloakServlet.HAWTIO_KEYCLOAK_CLIENT_CONFIG) != null) {
            keycloakConfigFile = System.getProperty(KeycloakServlet.HAWTIO_KEYCLOAK_CLIENT_CONFIG);
}
```
@vivek42 is there a chance you debug this fragment and check what's the `keycloakConfigFile` points to?

**Comment by tadayosi** [comment]
Let's close it as outdated.
