### ISSUE TITLE
Failed to load environment variables: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by MrEasy** [hawtio/hawtio#2605]
`io.hawt.blueprint.HawtioBlueprintContextListener.appendEnvironmentVariablesAndSystemProperties` iterates over system properties [here](https://github.com/hawtio/hawtio/blob/master/hawtio-base/src/main/java/io/hawt/blueprint/HawtioBlueprintContextListener.java#L106)

In case properties are programatically modified there is a race condition leading to ConcurrentModificationException below.
This is the same and can be fixed in the same manner like [KARAF-6337](https://issues.apache.org/jira/browse/KARAF-6337)

```
Failed to load environment variables:
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException: null
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1387) ~[?:?]
	at io.hawt.blueprint.HawtioBlueprintContextListener.appendEnvironmentVariablesAndSystemProperties(HawtioBlueprintContextListener.java:106) ~[663:io.hawt.hawtio-war:2.7.1]
	at io.hawt.blueprint.HawtioBlueprintContextListener.contextInitialized(HawtioBlueprintContextListener.java:93) ~[663:io.hawt.hawtio-war:2.7.1]
```

**Comment by MrEasy** [comment]
sent PR [2606](https://github.com/hawtio/hawtio/pull/2606)
