### ISSUE TITLE
Karaf 4.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by Maurice-Betzel** [hawtio/hawtio#2618]
Upgrade HAWTIO to use PAX logging version > 2.0.0 for Karaf 4.3.0-SNAPSHOT:

 5 │ Active   │   8 │ 2.0.2          │ OPS4J Pax Logging - API

karaf@root()> feature:repo-add hawtio 2.8.0
Adding feature url mvn:io.hawt/hawtio-karaf/2.8.0/xml/features
karaf@root()> feature:install hawtio
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=hawtio; type=karaf.feature; version="[2.8.0,2.8.0]"; filter:="(&(osgi.identity=hawtio)(type=karaf.feature)(version>=2.8.0)(version<=2.8.0))" [caused by: Unable to resolve hawtio/2.8.0: missing requirement [hawtio/2.8.0] osgi.identity; osgi.identity=hawtio-log; type=karaf.feature [caused by: Unable to resolve hawtio-log/2.8.0: missing requirement [hawtio-log/2.8.0] osgi.identity; osgi.identity=io.hawt.hawtio-log-osgi; type=osgi.bundle; version="[2.8.0,2.8.0]"; resolution:=mandatory [caused by: Unable to resolve io.hawt.hawtio-log-osgi/2.8.0: missing requirement [io.hawt.hawtio-log-osgi/2.8.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.ops4j.pax.logging.spi)(version>=1.8.0)(!(version>=2.0.0)))"]]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:434)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:421)
        at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
        at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:391)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve hawtio/2.8.0: missing requirement [hawtio/2.8.0] osgi.identity; osgi.identity=hawtio-log; type=karaf.feature [caused by: Unable to resolve hawtio-log/2.8.0: missing requirement [hawtio-log/2.8.0] osgi.identity; osgi.identity=io.hawt.hawtio-log-osgi; type=osgi.bundle; version="[2.8.0,2.8.0]"; resolution:=mandatory [caused by: Unable to resolve io.hawt.hawtio-log-osgi/2.8.0: missing requirement [io.hawt.hawtio-log-osgi/2.8.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.ops4j.pax.logging.spi)(version>=1.8.0)(!(version>=2.0.0)))"]]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve hawtio-log/2.8.0: missing requirement [hawtio-log/2.8.0] osgi.identity; osgi.identity=io.hawt.hawtio-log-osgi; type=osgi.bundle; version="[2.8.0,2.8.0]"; resolution:=mandatory [caused by: Unable to resolve io.hawt.hawtio-log-osgi/2.8.0: missing requirement [io.hawt.hawtio-log-osgi/2.8.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.ops4j.pax.logging.spi)(version>=1.8.0)(!(version>=2.0.0)))"]
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 13 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve io.hawt.hawtio-log-osgi/2.8.0: missing requirement [io.hawt.hawtio-log-osgi/2.8.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.ops4j.pax.logging.spi)(version>=1.8.0)(!(version>=2.0.0)))"
        at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1341)
        ... 14 more
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=hawtio; type=karaf.feature; version="[2.8.0,2.8.0]"; filter:="(&(osgi.identity=hawtio)(type=karaf.feature)(version>=2.8.0)(version<=2.8.0))" [caused by: Unable to resolve hawtio/2.8.0: missing requirement [hawtio/2.8.0] osgi.identity; osgi.identity=hawtio-log; type=karaf.feature [caused by: Unable to resolve hawtio-log/2.8.0: missing requirement [hawtio-log/2.8.0] osgi.identity; osgi.identity=io.hawt.hawtio-log-osgi; type=osgi.bundle; version="[2.8.0,2.8.0]"; resolution:=mandatory [caused by: Unable to resolve io.hawt.hawtio-log-osgi/2.8.0: missing requirement [io.hawt.hawtio-log-osgi/2.8.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.ops4j.pax.logging.spi)(version>=1.8.0)(!(version>=2.0.0)))"]]]

**Comment by tadayosi** [comment]
Yes, currently hawtio-log-osgi depends on Pax Logging 1.8.x:
https://github.com/hawtio/hawtio/blob/hawtio-2.9.0/hawtio-log-osgi/pom.xml#L48
```
$ bnd hawtio-log-osgi/target/hawtio-log-osgi-2.9.0.jar
[...]
Import-Package                           org.osgi.framework;version="[1.5,2)",org.apache.karaf.log.core;version="[3,5)",com.fasterxml.jackson.annotation;version="[2.8,3)",com.fasterxml.jackson.databind;version="[2.8,3)",io.hawt.log;version="[2.9,3)",io.hawt.log.support;version="[2.9,3)",org.ops4j.pax.logging.spi;version="[1.8,2)",org.slf4j;version="[1.7,2)",org.osgi.framework.wiring;version="[1.0,2)"
```

@jamesnetherton @grgrzybek Should we upgrade it to Pax Logging 2.0.x?

**Comment by grgrzybek** [comment]
Karaf 4.3.0.CR1 is being voted right now. Pax Logging 2 is an implementation of OSGi Cmpn R7 Logging Service 1.4 (while Pax Logging 1 is for OSGi Cmpn R6 Logging Service 1.3).
My recommendation is - wherever possible, hawtio should import only Slf4J packages (version didn't change between Pax Logging 1 and 2).

hawtio-log-osgi (which explicitly needs Pax Logging) can switch to whatever Pax Logging it needs, but to make it working on Karaf 4.2.x too (which I think is a good idea), should _explicitly_ specify version range:
```
org.ops4j.pax.logging.spi;version="[1.8,3)"
```
