### ISSUE TITLE
Unable to start without a home directory

### ISSUE THREAD

**Issue by s-spindler** [hawtio/hawtio#2644]
hawt does not start when there is no home directory for the executing user:
```
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@2a18f23c{/hawtio,null,UNAVAILABLE}{/tmp/jetty/hawtio-227666160106012995.war}
java.lang.IllegalStateException: Temp dir /home/application_user/.hawtio/tmp not useable: writeable=false, dir=false
	at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:388)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:264)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:69)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:506)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:544)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
	at org.eclipse.jetty.server.Server.start(Server.java:452)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.hawt.embedded.Main.run(Main.java:116)
	at io.hawt.embedded.Main.run(Main.java:78)
	at io.hawt.app.App.main(App.java:100)
```
In this case the `application_user` does not have a home directory. Is there a way of configuring another directory?

**Comment by tadayosi** [comment]
@s-spindler You can try changing the `user.home` system property to somewhere else when launching Hawtio.

**Comment by s-spindler** [comment]
@tadayosi Thanks for the tip, that worked!
I wonder if the error message could already contain such a hint but from what I see this is jetty code...
Closing here.
