### ISSUE TITLE
Exception when using hawtio war file along with camel jar file

### ISSUE THREAD

**Issue by juanpac** [hawtio/hawtio#2655]
Camel versions: 3.4.x

Hawito versions: 2.10.x  & 2.11.0

jetty version from camel package

Then i got this exception every time it starts

```
emq-data/localhost only has 44690 mb of usable space. - resetting to maximum available disk space: 44690 mb
Oct10.11:18:00 [main] INFO  | broker.TransportConnector:start  - Connector vm://localhost started
Oct10.11:18:00 [main] INFO  | engine.InternalRouteStartupManager:log  - Route: queue.inc.queue started and consuming from: jms://queue.inc.queue
Oct10.11:18:00 [main] INFO  | engine.AbstractCamelContext:doStartContext  - Total 48 routes, of which 46 are started
Oct10.11:18:00 [main] INFO  | engine.AbstractCamelContext:doStartContext  - Apache Camel 3.4.4 (camel-1) started in 1.680 seconds
Oct10.11:18:00 [main] INFO  | interceptor.InterceptorMain:main  - Starting Application
Implicitly setting Scheme = http
Oct10.11:18:00 [main] INFO  | jetty:run  - Using temp directory for jetty: /Users/juanpac/.hawtio/tmp
Embedded Hawtio: You can use --help to show usage
Using options [
    war=/Volumes/Extra/DevOps/camel/camel-jetty-rest/target/lib/hawtio-wildfly-2.11.0.war
    contextPath=/hawtio
    host=0.0.0.0
    port=8092
    plugins=plugins
    openUrl=true
    jointServerThread=false
    help=false]
About to start Hawtio /Volumes/Extra/DevOps/camel/camel-jetty-rest/target/lib/hawtio-wildfly-2.11.0.war
Oct10.11:18:00 [main] INFO  | server.Server:doStart  - jetty-9.4.31.v20200723; built: 2020-07-23T17:57:36.812Z; git: 450ba27947e13e66baa8cd1ce7e85a4461cacc1d; jvm 14.0.2+12-46
Oct10.11:18:01 [main] WARN  | webapp.WebAppContext:doStart  - Failed startup of context o.e.j.w.WebAppContext@432a6a69{/hawtio,file:///Users/juanpac/.hawtio/tmp/webapp/,UNAVAILABLE}{/Volumes/Extra/DevOps/camel/camel-jetty-rest/target/lib/hawtio-wildfly-2.11.0.war}
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:83)
    at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:70)
    at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:407)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1461)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:855)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
    at org.eclipse.jetty.server.Server.start(Server.java:408)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
    at org.eclipse.jetty.server.Server.doStart(Server.java:372)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
    at io.hawt.embedded.Main.run(Main.java:116)
    at io.hawt.embedded.Main.run(Main.java:78)
    at interceptor.InterceptorMain.main(InterceptorMain.java:156)
Caused by: java.lang.IllegalAccessError: class org.eclipse.jetty.webapp.StandardDescriptorProcessor tried to access protected method 'java.lang.Object org.eclipse.jetty.server.handler.ContextHandler$StaticContext.createInstance(java.lang.Class)' (org.eclipse.jetty.webapp.StandardDescriptorProcessor and org.eclipse.jetty.server.handler.ContextHandler$StaticContext are in unnamed module of loader 'app')
    at org.eclipse.jetty.webapp.StandardDescriptorProcessor.newListenerInstance(StandardDescriptorProcessor.java:1948)
    at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1903)
    ... 25 more
Oct10.11:18:01 [main] INFO  | server.AbstractConnector:doStart  - Started ServerConnector@4cd5fc46{HTTP/1.1, (http/1.1)}{0.0.0.0:8092}
Oct10.11:18:01 [main] INFO  | server.Server:doStart  - Started @6817ms

Welcome to Hawtio
=====================================================

http://localhost:8092/hawtio 
```

The only way to fix it (or at least workaround it) is to downgrade the jetty version to 3.3.0. like this

```
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-jetty</artifactId>
      <version>3.3.0</version>
    </dependency>
```

any jetty version newer than that will make the exception be thrown again

I have looked at the jetty changelog after that, but it seems like that are many changes and none of those is trivially associated with something related to the exception description.

**Comment by tadayosi** [comment]
The version used to build hawtio-embedded is a bit outdated. It's possible that the version conflicts with that from camel-jetty.

        <jetty-version>9.4.6.v20170531</jetty-version>

Let's upgrade the jetty version and release Hawtio 2.11.1 to see if it solves the issue.

**Comment by tadayosi** [comment]
Released 2.11.1. Please check.

**Comment by tadayosi** [comment]
Can you provide us with a reproducer?

**Comment by juanpac** [comment]
hey, i looked around trying to find out what a reproducer means  
Could you please elaborate?, is it a full prototype where you can see the problem happening in a forked project or something like that?

**Comment by tadayosi** [comment]
If it can be a single spring-boot project then it's just enough to provide us with a github repo url. Otherwise provide us with the exact steps to set up an env and run the Camel app so that we can replicate the reported issue at our ends.
