### ISSUE TITLE
unable to run hawtio-app-2.14.2

### ISSUE THREAD

**Issue by narsi-nallamilli** [hawtio/hawtio#2718]
I am unable to run standalone hawtio 2.14.2. I tried to run with java 11 and 8 but no success.

PS C:\Users\Narsi Nallamilli\Downloads> & 'C:\Program Files\Amazon Corretto\jdk1.8.0_312\bin\java.exe' -jar .\hawtio-app-2.14.2.jar
[main] INFO jetty - Logging initialized @225ms to org.eclipse.jetty.util.log.Slf4jLog
Implicitly setting Scheme = http
[main] INFO jetty - Using temp directory for jetty: C:\Users\Narsi Nallamilli\.hawtio\tmp
Embedded Hawtio: You can use --help to show usage
Using options [
        war=C:\Users\Narsi Nallamilli\AppData\Local\Temp\hawtio-8889076448176289581.war
        contextPath=/hawtio
        host=0.0.0.0
        port=8080
        extraClassPath=file:/C:/Program%20Files/Amazon%20Corretto/jdk1.8.0_312/lib/tools.jar
        plugins=plugins
        openUrl=true
        jointServerThread=false
        help=false]
About to start Hawtio C:\Users\Narsi Nallamilli\AppData\Local\Temp\hawtio-8889076448176289581.war
[main] INFO org.eclipse.jetty.server.Server - jetty-9.4.43.v20210629; built: 2021-06-30T11:07:22.254Z; git: 526006ecfa3af7f1a27ef3a288e2bef7ea9dd7e8; jvm 1.8.0_312-b07
[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@4157f54e{/hawtio,null,STOPPED}{C:\Users\Narsi Nallamilli\AppData\Local\Temp\hawtio-8889076448176289581.war}
java.lang.IllegalStateException: Failed to delete temp dir C:\Users\Narsi Nallamilli\.hawtio\tmp
        at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:532)
        at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:424)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:140)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:423)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.hawt.embedded.Main.run(Main.java:116)
        at io.hawt.embedded.Main.run(Main.java:78)
        at io.hawt.app.App.main(App.java:100)
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@2e5c649{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[main] INFO org.eclipse.jetty.server.Server - Started @407ms

Welcome to Hawtio
=====================================================

http://localhost:8080/hawtio

**Comment by sciencepal** [comment]
Failed to delete temp dir C:\Users\Narsi Nallamilli.hawtio\tmp

Could be a space issue.

**Comment by prahaladhchandrahasan** [comment]
Hello @narsi-nallamilli !
We tried to reproduce your issue in a windows 11 issue and we couldn't reproduce it. We have also tried it with Amazon Corretto 11.0.14_10 and jdk11.
However a small correction instead of `C:\Users\Narsi Nallamilli.hawtio\tmp` it should be `C:\Users\Narsi Nallamilli\.hawtio\tmp` if that is a typo then please ignore it. 
Please provide us more details so that we can resolve your issue.
