### ISSUE TITLE
Unable to download Flight Recorder recordings

### ISSUE THREAD

**Issue by illidan80** [hawtio/hawtio#2724]
I running a Spring Boot 2.3 application inside Docker container. I using Azul Java 11.

Inside, I using  `group: 'io.hawt', name: 'hawtio-springboot', version: '2.14.1'` dependency with the following configuration:

```
spring.jmx.enabled=true
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,jolokia,hawtio
management.endpoint.health.show-details=always
management.endpoint.health.group.readiness.include=*
management.endpoint.health.group.liveness.include=ping
hawtio.authenticationEnabled=false
```

I able to access "Diagnostics" tab and to start recording. After I stop recording, new recording row added to the list of the recordings with download button in the "File/Download" column.

When I clicking download button, a file downloaded always with the same content:

`{"request":{"mbean":"jdk.management.jfr:type=FlightRecorder","arguments":["6"],"type":"exec","operation":"downloadRecording(long)"},"error_type":"java.lang.IllegalArgumentException","error":"java.lang.IllegalArgumentException : No operation downloadRecording found on MBean jdk.management.jfr:type=FlightRecorder","status":400}`

If I looking into[ exposed operations of the FlightRecorderMXBean](https://docs.oracle.com/en/java/javase/12/docs/api/jdk.management.jfr/jdk/management/jfr/FlightRecorderMXBean.html), indeed there is no such operation such as "downloadRecording".

What do I missing? How I can download / export recorded recordings? Where they are expected to be stored on the file system?

**Comment by tadayosi** [comment]
The `downloadRecording(long)` virtual method is implemented as a servlet filter here:
https://github.com/hawtio/hawtio/blob/master/hawtio-system/src/main/java/io/hawt/web/filters/FlightRecordingDownloadFacade.java

> When I clicking download button, a file downloaded always with the same content:

What do you mean by this?  At least it looks like you can download something with the button.

**Comment by illidan80** [comment]
@tadayosi 

> What do you mean by this? At least it looks like you can download something with the button.

Please see screenshot attached

![image](https://user-images.githubusercontent.com/53393926/149907442-6d8ee345-82da-415c-aa15-0f5c03749f5a.png)

**Comment by tadayosi** [comment]
Yes, but the same button always downloading the same file seems to be working as expected.

**Comment by illidan80** [comment]
Well, on my environment I getting the error I described...

**Comment by tadayosi** [comment]
@illidan80 Thanks for your investigation. I see what's the problem now. No it's not your responsibility it's indeed a bug in hawtio-springboot. I'll fix it soon. Thanks for reporting.

**Comment by tadayosi** [comment]
In the meantime, as a workaround you can register the filter by yourself and the feature should be available for the existing versions.

**Comment by tadayosi** [comment]
Even after adding the filter to Spring Boot I found there's still an issue with the filter:
```
java.lang.IllegalStateException: UT010005: Cannot call getOutputStream(), getWriter() already called
	at io.undertow.servlet.spec.HttpServletResponseImpl.getOutputStream(HttpServletResponseImpl.java:360) ~[undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
	at io.hawt.web.filters.FlightRecordingDownloadFacade.downloadFlightRecording(FlightRecordingDownloadFacade.java:92) ~[hawtio-system-2.15-SNAPSHOT.jar:2.15-SNAPSHOT]
	at io.hawt.web.filters.FlightRecordingDownloadFacade.doFilter(FlightRecordingDownloadFacade.java:66) ~[hawtio-system-2.15-SNAPSHOT.jar:2.15-SNAPSHOT]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
	at io.hawt.web.auth.LoginRedirectFilter.doFilter(LoginRedirectFilter.java:63) ~[hawtio-system-2.15-SNAPSHOT.jar:2.15-SNAPSHOT]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:43) ~[hawtio-system-2.15-SNAPSHOT.jar:2.15-SNAPSHOT]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) ~[undertow-servlet-2.2.14.Final.jar:2.2.14.Final]
```

I need to investigate it and fix the filter.

**Comment by illidan80** [comment]
@tadayosi Thank you. Also, please test with Tomcat - I was getting NullPointerException after manually adding the filter

**Comment by tadayosi** [comment]
@skarsaune The flight recorder downloading seems to be not working for a long time. Do you have any ideas on how to fix it?

**Comment by skarsaune** [comment]
@tadayosi : Hmm need to investigate a bit. Will try to have a look later.

**Comment by skarsaune** [comment]
Probably need to cater for differences in servlet containers. Will try to reproduce.

**Comment by skarsaune** [comment]
I am having some problems running the integration tests in hawtio-springboot. Tried to use hawtio-springboot from a spring boot application as @illidan80 reports, but have some problems loading the hawtio plugins.

**Comment by tadayosi** [comment]
@skarsaune What I normally do is as follows:
```sh
mvn clean install
mvn spring-boot:run -pl examples/springboot
```
If you have problems with springboot itests then you can try `mvn clean install -DskipTests`.

Once you've launched the spring boot example you can access the console at http://localhost:10001/actuator/hawtio/

**Comment by illidan80** [comment]
@skarsaune please note it doesn't play well with tomcat as well (tested with 9.0.56)

**Comment by skarsaune** [comment]
@tadayosi : Well, I guess I suspected this may come back to bite me one day. One question during debugging: It seems that the request from the frontend is `/actuator/hawtio/jolokia/.....` but somewhere within the handing of the request it tuns into `/actuator/jolokia/..` . I don't completely follow what goes on there.

**Comment by tadayosi** [comment]
@skarsaune Yes, `/actuator/hawtio/jolokia/` is redirected to `/actuator/jolokia/` with the controller. We need this because Spring Boot already has the built-in Jolokia endpoint feature and we want to reuse it instead of bringing our own Jolokia for a Spring Boot app.

Could it be the cause of the flight recorder downloading issue?

**Comment by tadayosi** [comment]
FYI, after the comment I thought adding `/jolokia/*` to this line might fix the issue so tried, but it doesn't fix it.
https://github.com/hawtio/hawtio/blob/main/platforms/springboot/src/main/java/io/hawt/springboot/HawtioManagementConfiguration.java#L224-L225

**Comment by skarsaune** [comment]
Thanks. I think I was onto something last night, but had to leave it there. I am leaving for a few days on a short winter break today though. To cabin without water, electricity or network :-) So the fix will be on hold for a bit still.

**Comment by tadayosi** [comment]
@skarsaune No worries. Thanks for looking into it!

**Comment by skarsaune** [comment]
I've been going down a rabbit hole for quite a while trying to get around the spring request dispatching, getting messier and messier. I think I perhaps should shift focus to see why it is failing in tomcat to see if there is a cleaner solution there. In the meantime I suppose we could disable the download support if `io.hawt.config:name=configFacade,type=ConfigFacade` is present (as a detection of Hawtio Spring boot)

**Comment by skarsaune** [comment]
@illidan80 : I have tested in tomcat 9.0.55 running in Eclipse and am not able to reproduce any problem. Do you have details on the problems you experienced with tomcat?

**Comment by tadayosi** [comment]
I think @illidan80 is talking about the default spring-boot-starter-tomcat. So according to Martin's investigation it looks like it's the issue with Spring Boot. At this moment, we have to say that the flight recorder feature doesn't work well with Spring Boot.

**Comment by prahaladhchandrahasan** [comment]
Since it's an issue with Spring Boot itself can we remove the bug tag?? @tadayosi @skarsaune

**Comment by illidan80** [comment]
@prahaladhchandrahasan 

Its not a "Spring Boot itself" but your implementation of the integration between Hawtio and Spring Boot. I even specified the exact package which contains the issue:

`group: 'io.hawt', name: 'hawtio-springboot', version: '2.14.1'`

If you will debug the code, you will see that its about your specific implementation for downloading of recordings files. I was able to locate these files in Tomcat's temp folder and download them manually by opening SSH to target machine...

I suggesting to look into that specific place, which currently based on Spring filters, and reimplement it to use something more standard. After all, it just a simple task to download a file stored on file system...

**Comment by prahaladhchandrahasan** [comment]
Okay thanks @illidan80 . Will look into that.

**Comment by skarsaune** [comment]
@illidan80 : You are correct it is a problem with the servlet filter that does not play well within the springboot and undertow web stack. The problem only occurs when you embed hawtio in the spring boot application under /actuator/hawtio. 
There is no generic functionality to download local files over JMX. Instead it is read in successive 50k blocks that are written to the response one by one. That is important as flight recordings can be huge, and might use up the memory of both the server and client.
I have been debugging this on and off for weeks, but the workarounds I have tried were messy and did not work. 
Frontend workaround:
I was mistaken that there was an MBean to easily detect the fact that it is hawtio-springboot. Looking through the JMX tree I see some possiblities. for the frontend until we find a backend solution e.g.
IF 
* hawtio url contains /actuator/hawtio
THEN
* Provide file:/ link instead of `downloadRecording(...)` link

**Comment by skarsaune** [comment]
@asterioproba : That link appears to go straight to Jolokia. The downloadrecording is kind of an illusion and is only supported when you go via the hawtio proxy.

**Comment by tadayosi** [comment]
@asterioproba Yes, I don't think the link works on Hawtio Online. We should disable the link if the plugin detects it's on Hawtio Online.

**Comment by mklueh** [comment]
Trying to understand the conclusion, is this something that will be fixed and work in future?

**Comment by tadayosi** [comment]
@mklueh We are now in the middle of Hawtio v3 development https://github.com/hawtio/hawtio/discussions/2828, but Flight Recorder plugin is not in the initial scope.

The issue is not fixed yet with Spring Boot, but we don't have much time to revisit it. Contributions are always welcome.

**Comment by tadayosi** [comment]
@grgrzybek Since you assigned yourself to hawtio/hawtio-next#643, let me assign it to you as well.

**Comment by grgrzybek** [comment]
Superseded by:
* hawtio/hawtio-next#643
