### ISSUE TITLE
NoClassDefFoundError starting version 4.0-RC1 

### ISSUE THREAD

**Issue by ssadedin** [hawtio/hawtio#3337]
I have an app where I embedded Hawtio. It works great with the war files from 3.x and 2.x but when I downloaded the 4.x war files (beta and RC1) I get the following error when starting up:

```
16:32:40.925 [main] WARN  o.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@24b52d3e{hawtio,/hawtio,file:///Users/xxxxx/.hawtio/tmp/webapp/,UNAVAILABLE}{/Users/xxxxx/camel/hawtio/hawtio-war-4.0-beta-1.war}
java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:637)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:515)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.jetty.util.Loader.loadClass(Loader.java:64)
	at org.eclipse.jetty.servlet.BaseHolder.doStart(BaseHolder.java:89)
	at org.eclipse.jetty.servlet.ListenerHolder.doStart(ListenerHolder.java:72)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1457)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1422)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at io.hawt.embedded.Main.run(Main.java:116)
	at io.hawt.embedded.Main.run(Main.java:78)
	at io.hawt.embedded.Main$run$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at camelpack.Application.main(Application.groovy:31)
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletContextListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:489)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 39 common frames omitted
	Suppressed: java.lang.ClassNotFoundException: jakarta.servlet.ServletContextListener
		at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
		at org.eclipse.jetty.webapp.WebAppClassLoader.findClass(WebAppClassLoader.java:637)
		at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:515)
		... 40 common frames omitted
16:32:40.940 [main] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@1255b1d1{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
16:32:40.940 [main] INFO  org.eclipse.jetty.server.Server - Started @1083ms
```

I tried a few things with adding the servlet API to the classpath of the hosting application, but they didn't work. 

Are there new instructions for how to embed the 4.x versions that are different to 3.x and 2.x?

**Comment by tadayosi** [comment]
Hi, which version of Jetty are you using?  Hawtio 4.x includes upgrade from JEE 8 -> Jakarta EE 9, which requires to use Jetty >=11.
https://hawt.io/docs/versions.html

**Comment by ssadedin** [comment]
thanks! that helped me solve it.

In fact, I had a stray reference that was bringing in the old jetty version in my Gradle build file. After I removed that it worked.
