### ISSUE TITLE
hawtio-springboot doesn't work well with Spring Boot customization of paths

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio#3369]
Spring Boot offers 3 implementations of `org.springframework.boot.web.servlet.server.AbstractServletWebServerFactory` - for Jetty, Tomcat and Undertow.

When you add `spring-boot-starter-web` you get one server (by default it's Tomcat), when you add `spring-boot-starter-actuator` **and** `server.port` property is different than `management.server.port`, you get another server.

while these (Jetty, Tomcat, Undertow) are fully compatible JakartaEE servlet containers where you are able to deploy multiple WARs (web applications) with separate _context path_ each, in embedded scenario, there's no need for multiple _contexts_ - one is enough (per server).

But you can kind of _shift_ the single _context_ to be available under non default (non _ROOT_) context path. This is done separately for non-management and management servers using these properties respectively:
* `server.servlet.context-path`
* `management.server.base-path` (IMO, should be `management.server.servlet.context-path`)

In pure JakartaEE scenario, the context path (the two above) are determined by WAR (e.g., Tomcat's `webapps/hawtio.war` means `/hawtio` context path).

Then in JakartaEE, `WEB-INF/web.xml` comes into play with its servlet mappings (if not specified, there's always a _default_ servlet with `/` mapping handling resources).

In Spring Boot which uses Spring MVC (in most cases, not counting WebFlux) we usually don't invoke servlets directly, but rather through `org.springframework.web.servlet.HandlerAdapter` invoked by single `org.springframework.web.servlet.DispatcherServlet`.
This means that in Spring you have one top-level servlet. And it has to be mapped. So you have these settings for non-management and management servers:
* `spring.mvc.servlet.path` (defaults to "/")
* ... nothing! you can't configure the mapping for DispatcherServlet used by management server. However if you don't specify separate `management.server.port`, there's only one server, context and dispatcher servlet mapping, so you have the above...
`spring.mvc.servlet.path` (or non-configurable `/` for management server's DispatcherServlet) is used in `org.springframework.boot.autoconfigure.web.servlet.DispatcherServletRegistrationBean`

Is this everything? Well, not quite.

For management server (if `management.server.port` is different than `server.port`, i.e., there are two servers) you can actually change the default `/actuator` prefix with:
* `management.endpoints.web.base-path`

Finally, the endpoints get their URI suffix using ID. Which can be remapped with:
* management.endpoints.web.path-mapping.hawtio = my-hawtio
* management.endpoints.web.path-mapping.health = am-i-working
* ...

So for example with this configuration:
```
server.servlet.context-path=/ctx
spring.mvc.servlet.path=/d
management.server.base-path=/mgmt-ctx
management.endpoints.web.base-path=/endpoints
management.endpoints.web.path-mapping.hawtio = my-hawtio

management.endpoints.web.exposure.include=hawtio,jolokia,health
```

and one `@Controller` (which goes to non-management server):
```java
@Controller
public class HelloController {
    @RequestMapping("/")
    @ResponseBody
    public String hello() {
        return "Hello World!";
    }
}
```

You should be able to use these URLs:
* http://localhost:10000/ctx/d/ to access HelloController
* http://localhost:10001/mgmt-ctx/endpoints/health to access `health` endpoint
* http://localhost:10001/mgmt-ctx/endpoints/jolokia/version to call Jolokia's `version` handler
* http://localhost:10001/mgmt-ctx/endpoints/my-hawtio to access Hawtio

However with current usage of `io.hawt.springboot.EndpointPathResolver` we can't access Hawtio and we're getting HTTP 500 caused by:
```
java.io.IOException: UT010029: Stream is closed
	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:139)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:131)
	at io.hawt.web.filters.BaseTagHrefFilter.doFilter(BaseTagHrefFilter.java:75)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:258)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:183)
	at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:188)
	at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:136)
	at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:99)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:171)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1431)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1167)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:276)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:132)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:256)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:101)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:859)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

`BaseTagHrefFilter` shouldn't be called at all - this is because DispatcherServlet is in the process of rendering a view with this name:
```
forward:/d/endpoints/my-hawtio/index.html
```

However it should be:
```
forward:/endpoints/my-hawtio/index.html
```

(it shouldn't be `forward:/mgmt-ctx/endpoints/my-hawtio/index.html`, because `forward:` URIs are context-relative).

When I used correct `forward:/endpoints/my-hawtio/index.html`, the returned HTML (with HTTP 200) isn't correct... It contains:
```html
<!doctype html>
<html lang="en">
<head>
...
  <base href="/hawtio/">
  <link rel="icon" href="/hawtio/favicon.ico">
  <script defer="defer" src="/hawtio/static/js/main.4320fdb6.js"></script>
</head>
<body>
...
```

* base should be `/mgmt-ctx/endpoints/my-hawtio/`
* URLs should be for example `/mgmt-ctx/endpoints/my-hawtio/static/js/main.4320fdb6.js`

**Comment by grgrzybek** [comment]
PR: #3373
