### ISSUE TITLE
Can't configure standalone Jetty for hawtio authentication

### ISSUE THREAD

**Issue by grgrzybek** [hawtio/hawtio#3398]
The instructions at https://hawt.io/docs/security.html#_jetty already mention problems with Jetty.

The problem is:
```
15:57:14 WARN {qtp191382150-33} : Login failed due to: java.lang.NullPointerException: Cannot invoke "org.eclipse.jetty.jaas.JAASLoginService.getBean(java.lang.Class)" because the return value of "java.lang.ThreadLocal.get()" is null
	at org.eclipse.jetty.jaas.spi.PropertyFileLoginModule.setupPropertyUserStore(PropertyFileLoginModule.java:71)
	at org.eclipse.jetty.jaas.spi.PropertyFileLoginModule.initialize(PropertyFileLoginModule.java:56)
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:745)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:679)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:677)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:677)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at io.hawt.system.Authenticator.login(Authenticator.java:210)
	at io.hawt.system.Authenticator.doAuthenticate(Authenticator.java:184)
	at io.hawt.system.Authenticator.authenticate(Authenticator.java:155)
	at io.hawt.web.auth.LoginServlet.doPost(LoginServlet.java:68)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:520)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
...
```

and the reason is that `org.eclipse.jetty.jaas.spi.PropertyFileLoginModule` requires a web application with proper `<login-config>`, while Hawtio has custom authentication.

It'd be nice to provide easy way for people who want to use Jetty.

**Comment by grgrzybek** [comment]
Additionally I'm getting HTTP 500:

```
jakarta.servlet.ServletException: logout failed
	at org.eclipse.jetty.ee10.servlet.ServletApiRequest.logout(ServletApiRequest.java:626)
	at jakarta.servlet.http.HttpServletRequestWrapper.logout(HttpServletRequestWrapper.java:293)
	at io.hawt.web.auth.LogoutServlet.doGet(LogoutServlet.java:38)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1379)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1619)
	at io.hawt.web.auth.ClientRouteRedirectFilter.doFilter(ClientRouteRedirectFilter.java:144)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1591)
	at io.hawt.web.filters.HttpHeaderFilter.doFilter(HttpHeaderFilter.java:56)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
...
```

**Comment by tadayosi** [comment]
I thought that's something that should be fixed at Jetty side. Maybe this one? jetty/jetty.project#6223. It was closed without fix just because no further info was provided.

**Comment by grgrzybek** [comment]
Doc PR: hawtio/website#64

**Comment by grgrzybek** [comment]
Dev PR:
* #3795
