### ISSUE TITLE
OidcConfiguration cannot deal with httpProxy

### ISSUE THREAD

**Issue by norbert-ka** [hawtio/hawtio#3659]
Trying to use OpenID-Connect with hawtio and configuring a proxy in the oidc properties results in an exception:

```
java.net.UnknownHostException: http
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533) ~[?:?]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385) ~[?:?]
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306) ~[?:?]
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:401) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~[httpclient-4.5.14.jar:4.5.14]
        at io.hawt.web.auth.oidc.OidcConfiguration.fetchJSON(OidcConfiguration.java:577) [hawtio-system-4.0.0.jar:4.0.0]
        at io.hawt.web.auth.oidc.OidcConfiguration.buildConfiguration(OidcConfiguration.java:437) [hawtio-system-4.0.0.jar:4.0.0]
```

This is due to a typo in class io.hawt.web.auth.oid.OidcConfiguration method  buildHttpClient.  In line 377 the URI-Scheme is taken as the hostname instead of the actual hostname (uri.getHost()):

```
376            String scheme = uri.getScheme();
377            String host = uri.getScheme();
378            int port = uri.getPort();
```

**Comment by grgrzybek** [comment]
Good catch - thanks @norbert-ka !
