### ISSUE TITLE
Hawtio Quarkus Undertow

### ISSUE THREAD

**Issue by AfifRana** [hawtio/hawtio#3738]
I am using undertow in camel quarkus. I try to add hawtio to my project. But i got this error :

```
Caused by: java.lang.AbstractMethodError: Receiver class io.quarkus.undertow.runtime.DelegatingResourceManager does not define or inherit an implementation of the resolved method 'abstract boolean isResourceChangeListenerSupported()' of interface io.undertow.server.handlers.resource.ResourceManager.
        at io.undertow.servlet.handlers.ServletPathMatches.<init>(ServletPathMatches.java:86)
        at io.undertow.servlet.core.DeploymentImpl.<init>(DeploymentImpl.java:95)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:151)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:545)
        at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy(Unknown Source)
```

What I have :
- Camel undertow dependency
```
   <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-undertow</artifactId>
      <version>4.0.0.redhat-00036</version>
    </dependency>
```
- Rest configuration undertow
```
       restConfiguration()
            .enableCORS(true)
            .component("undertow")
            .port("9090");

        rest("/4.0.0")
            .get("/echo")
            .produces("application/json")
            .to("direct:echoRoute")
```
- Hawtio dependency
```
   <dependency>
      <groupId>io.hawt</groupId>
      <artifactId>hawtio-quarkus</artifactId>
      <version>4.0.0.redhat-00072</version>
    </dependency>
```
- I only add this in my application.properties
```
# hawtio
quarkus.hawtio.authenticationEnabled = false
```
- Version of camel
```
      <dependency>
        <groupId>com.redhat.quarkus.platform</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>3.2.10.Final-redhat-00002</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.redhat.quarkus.platform</groupId>
        <artifactId>quarkus-camel-bom</artifactId>
        <version>3.2.10.Final-redhat-00002</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

I have look around to the github repository and found this

DelegatingResourceManager implementation
- io.hawt:hawtio-quarkus:jar:4.0.0.redhat-00072:compile
- io.quarkus:quarkus-undertow:jar:3.2.10.Final-redhat-00003:compile
Link :
[quarkus/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/DelegatingResourceManager.java at 3.2.10.Final · quarkusio/quarkus · GitHub](https://github.com/quarkusio/quarkus/blob/3.2.10.Final/extensions/undertow/runtime/src/main/java/io/quarkus/undertow/runtime/DelegatingResourceManager.java)

ResourceManager (interface) method isResourceChangeListenerSupported
- org.apache.camel:camel-undertow:jar:4.0.0.redhat-00036:compile
- io.undertow:undertow-core:jar:2.3.10.SP1-redhat-00001:compile
Link :
[undertow/core/src/main/java/io/undertow/server/handlers/resource/ResourceManager.java at 2.3.10.Final · undertow-io/undertow · GitHub](https://github.com/undertow-io/undertow/blob/2.3.10.Final/core/src/main/java/io/undertow/server/handlers/resource/ResourceManager.java)

Currently, my company want to using any redhat version of library.
What should I do to solve the error?

**Comment by AfifRana** [comment]
Another discussion https://github.com/quarkusio/quarkus/issues/45320

**Comment by jamesnetherton** [comment]
`camel-undertow` is not supported with Camel Quarkus. Use `camel-quarkus-platform-http` instead.

**Comment by AfifRana** [comment]
Ok, thanks for the recommendation. I will try it

**Comment by tadayosi** [comment]
As James said, for Camel Quarkus `camel-undertow` is not supported. Let me assume the issue is fixed and close this.
