### ISSUE TITLE
hawtio-default-offline is trying to contact Maven Central

### ISSUE THREAD

**Issue by rkettelerij** [hawtio/hawtio#442]
Currently the hawtio-default-offline distribution only prevents hawt.io from contacting GitHub. It should also avoid contacting Maven Central. 

Deploying the hawtio-default-offline distribution on a node with no internet access will lead to the following error:

```
2013-07-31 11:09:54,820 ERROR [] [io.hawt.maven.indexer.MavenIndexerFacade] (MavenIndexerFacade startup timer) Failed to update the maven repository indices: java.io.IOException: Transfer for nexus-maven-repository-index.properties failed; Error transferring file: Connection refused to http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties: java.io.IOException: Transfer for nexus-maven-repository-index.properties failed; Error transferring file: Connection refused to http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
    at org.apache.maven.index.updater.WagonHelper$WagonFetcher.retrieve(WagonHelper.java:241) [indexer-core-5.1.1.jar:5.1.1]
    at org.apache.maven.index.updater.WagonHelper$WagonFetcher.retrieve(WagonHelper.java:201) [indexer-core-5.1.1.jar:5.1.1]
    at org.apache.maven.index.updater.DefaultIndexUpdater.downloadIndexProperties(DefaultIndexUpdater.java:459) [indexer-core-5.1.1.jar:5.1.1]
    at org.apache.maven.index.updater.DefaultIndexUpdater.access$000(DefaultIndexUpdater.java:76) [indexer-core-5.1.1.jar:5.1.1]
    at org.apache.maven.index.updater.DefaultIndexUpdater$IndexAdaptor.setProperties(DefaultIndexUpdater.java:589) [indexer-core-5.1.1.jar:5.1.1]
    at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:814) [indexer-core-5.1.1.jar:5.1.1]
    at org.apache.maven.index.updater.DefaultIndexUpdater.fetchAndUpdateIndex(DefaultIndexUpdater.java:157) [indexer-core-5.1.1.jar:5.1.1]
    at io.hawt.maven.indexer.MavenIndexerFacade.downloadOrUpdateIndices(MavenIndexerFacade.java:171) [hawtio-maven-indexer-1.2-M2.jar:]
    at io.hawt.maven.indexer.MavenIndexerFacade.init(MavenIndexerFacade.java:136) [hawtio-maven-indexer-1.2-M2.jar:]
    at io.hawt.maven.indexer.AsyncMavenIndexerFacadeFactory.createMavenIndexer(AsyncMavenIndexerFacadeFactory.java:129) [hawtio-maven-indexer-1.2-M2.jar:]
    at io.hawt.maven.indexer.AsyncMavenIndexerFacadeFactory$1.run(AsyncMavenIndexerFacadeFactory.java:54) [hawtio-maven-indexer-1.2-M2.jar:]
    at java.util.TimerThread.mainLoop(Timer.java:512) [rt.jar:1.6.0_24]
    at java.util.TimerThread.run(Timer.java:462) [rt.jar:1.6.0_24]
Caused by: org.apache.maven.wagon.TransferFailedException: Error transferring file: Connection refused to http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
    at org.sonatype.maven.wagon.AhcWagon.fillInputData(AhcWagon.java:301) [wagon-ahc-1.2.1.jar:]
    at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116) [pax-url-aether-1.5.2.jar:]
    at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88) [pax-url-aether-1.5.2.jar:]
    at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61) [pax-url-aether-1.5.2.jar:]
    at org.apache.maven.index.updater.WagonHelper$WagonFetcher.retrieve(WagonHelper.java:219) [indexer-core-5.1.1.jar:5.1.1]
    ... 12 more
Caused by: java.io.IOException: Connection refused to http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
    at org.sonatype.maven.wagon.AhcWagon.fillInputData(AhcWagon.java:270) [wagon-ahc-1.2.1.jar:]
    ... 16 more
Caused by: java.net.ConnectException: Connection refused to http://repo1.maven.org/maven2/.index/nexus-maven-repository-index.properties
    at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:95) [async-http-client-1.6.5.jar:]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:381) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:372) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:334) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:389) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44) [netty-3.2.5.Final.jar:]
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [rt.jar:1.6.0_24]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [rt.jar:1.6.0_24]
    at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_24]
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) [rt.jar:1.6.0_24]
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567) [rt.jar:1.6.0_24]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354) [netty-3.2.5.Final.jar:]
    at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276) [netty-3.2.5.Final.jar:]
    ... 3 more

```

**Comment by cadre15** [comment]
Is there a configuration option to disable checking maven central?

**Comment by cadre15** [comment]
Have also tried dynamic settings as per attached screenshot.

![screenshot from 2016-07-24 15 16 15](https://cloud.githubusercontent.com/assets/19981351/17083992/d34fab32-51b1-11e6-914f-1a368d7dafdd.png)
